// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/audit.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditEvent is append-only history for administrative and operational mutations.
type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditEventId  string                 `protobuf:"bytes,1,opt,name=audit_event_id,json=auditEventId,proto3" json:"audit_event_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ActorType     string                 `protobuf:"bytes,4,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId       string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	ObjectType    string                 `protobuf:"bytes,7,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,8,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	RequestId     *string                `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Reason        *string                `protobuf:"bytes,11,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	BeforeState   *structpb.Struct       `protobuf:"bytes,12,opt,name=before_state,json=beforeState,proto3" json:"before_state,omitempty"`
	AfterState    *structpb.Struct       `protobuf:"bytes,13,opt,name=after_state,json=afterState,proto3" json:"after_state,omitempty"`
	Result        string                 `protobuf:"bytes,14,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_cerbero_contracts_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetAuditEventId() string {
	if x != nil {
		return x.AuditEventId
	}
	return ""
}

func (x *AuditEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuditEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditEvent) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *AuditEvent) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *AuditEvent) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *AuditEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AuditEvent) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *AuditEvent) GetBeforeState() *structpb.Struct {
	if x != nil {
		return x.BeforeState
	}
	return nil
}

func (x *AuditEvent) GetAfterState() *structpb.Struct {
	if x != nil {
		return x.AfterState
	}
	return nil
}

func (x *AuditEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AuditEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_cerbero_contracts_v1_audit_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_audit_proto_rawDesc = "" +
	"\n" +
	" cerbero/contracts/v1/audit.proto\x12\x14cerbero.contracts.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x04\n" +
	"\n" +
	"AuditEvent\x12$\n" +
	"\x0eaudit_event_id\x18\x01 \x01(\tR\fauditEventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x04 \x01(\tR\tactorType\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1f\n" +
	"\vobject_type\x18\a \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\b \x01(\tR\bobjectId\x12\"\n" +
	"\n" +
	"request_id\x18\t \x01(\tH\x00R\trequestId\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1b\n" +
	"\x06reason\x18\v \x01(\tH\x01R\x06reason\x88\x01\x01\x12:\n" +
	"\fbefore_state\x18\f \x01(\v2\x17.google.protobuf.StructR\vbeforeState\x128\n" +
	"\vafter_state\x18\r \x01(\v2\x17.google.protobuf.StructR\n" +
	"afterState\x12\x16\n" +
	"\x06result\x18\x0e \x01(\tR\x06result\x123\n" +
	"\bmetadata\x18\x0f \x01(\v2\x17.google.protobuf.StructR\bmetadataB\r\n" +
	"\v_request_idB\t\n" +
	"\a_reasonB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_audit_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_audit_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_audit_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_audit_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_audit_proto_rawDesc), len(file_cerbero_contracts_v1_audit_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_audit_proto_rawDescData
}

var file_cerbero_contracts_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbero_contracts_v1_audit_proto_goTypes = []any{
	(*AuditEvent)(nil),            // 0: cerbero.contracts.v1.AuditEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
}
var file_cerbero_contracts_v1_audit_proto_depIdxs = []int32{
	1, // 0: cerbero.contracts.v1.AuditEvent.occurred_at:type_name -> google.protobuf.Timestamp
	2, // 1: cerbero.contracts.v1.AuditEvent.before_state:type_name -> google.protobuf.Struct
	2, // 2: cerbero.contracts.v1.AuditEvent.after_state:type_name -> google.protobuf.Struct
	2, // 3: cerbero.contracts.v1.AuditEvent.metadata:type_name -> google.protobuf.Struct
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_audit_proto_init() }
func file_cerbero_contracts_v1_audit_proto_init() {
	if File_cerbero_contracts_v1_audit_proto != nil {
		return
	}
	file_cerbero_contracts_v1_audit_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_audit_proto_rawDesc), len(file_cerbero_contracts_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_audit_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_audit_proto_depIdxs,
		MessageInfos:      file_cerbero_contracts_v1_audit_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_audit_proto = out.File
	file_cerbero_contracts_v1_audit_proto_goTypes = nil
	file_cerbero_contracts_v1_audit_proto_depIdxs = nil
}
