// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/case.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CaseStatus is the governed investigation lifecycle.
type CaseStatus int32

const (
	CaseStatus_CASE_STATUS_UNSPECIFIED   CaseStatus = 0
	CaseStatus_CASE_STATUS_OPEN          CaseStatus = 1
	CaseStatus_CASE_STATUS_TRIAGE        CaseStatus = 2
	CaseStatus_CASE_STATUS_INVESTIGATING CaseStatus = 3
	CaseStatus_CASE_STATUS_ON_HOLD       CaseStatus = 4
	CaseStatus_CASE_STATUS_RESPONSE      CaseStatus = 5
	CaseStatus_CASE_STATUS_RESOLVED      CaseStatus = 6
	CaseStatus_CASE_STATUS_CLOSED        CaseStatus = 7
)

// Enum value maps for CaseStatus.
var (
	CaseStatus_name = map[int32]string{
		0: "CASE_STATUS_UNSPECIFIED",
		1: "CASE_STATUS_OPEN",
		2: "CASE_STATUS_TRIAGE",
		3: "CASE_STATUS_INVESTIGATING",
		4: "CASE_STATUS_ON_HOLD",
		5: "CASE_STATUS_RESPONSE",
		6: "CASE_STATUS_RESOLVED",
		7: "CASE_STATUS_CLOSED",
	}
	CaseStatus_value = map[string]int32{
		"CASE_STATUS_UNSPECIFIED":   0,
		"CASE_STATUS_OPEN":          1,
		"CASE_STATUS_TRIAGE":        2,
		"CASE_STATUS_INVESTIGATING": 3,
		"CASE_STATUS_ON_HOLD":       4,
		"CASE_STATUS_RESPONSE":      5,
		"CASE_STATUS_RESOLVED":      6,
		"CASE_STATUS_CLOSED":        7,
	}
)

func (x CaseStatus) Enum() *CaseStatus {
	p := new(CaseStatus)
	*p = x
	return p
}

func (x CaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_case_proto_enumTypes[0].Descriptor()
}

func (CaseStatus) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_case_proto_enumTypes[0]
}

func (x CaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseStatus.Descriptor instead.
func (CaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_case_proto_rawDescGZIP(), []int{0}
}

// CasePriority represents operational urgency independently from severity.
type CasePriority int32

const (
	CasePriority_CASE_PRIORITY_UNSPECIFIED CasePriority = 0
	CasePriority_CASE_PRIORITY_P1_CRITICAL CasePriority = 1
	CasePriority_CASE_PRIORITY_P2_HIGH     CasePriority = 2
	CasePriority_CASE_PRIORITY_P3_MEDIUM   CasePriority = 3
	CasePriority_CASE_PRIORITY_P4_LOW      CasePriority = 4
)

// Enum value maps for CasePriority.
var (
	CasePriority_name = map[int32]string{
		0: "CASE_PRIORITY_UNSPECIFIED",
		1: "CASE_PRIORITY_P1_CRITICAL",
		2: "CASE_PRIORITY_P2_HIGH",
		3: "CASE_PRIORITY_P3_MEDIUM",
		4: "CASE_PRIORITY_P4_LOW",
	}
	CasePriority_value = map[string]int32{
		"CASE_PRIORITY_UNSPECIFIED": 0,
		"CASE_PRIORITY_P1_CRITICAL": 1,
		"CASE_PRIORITY_P2_HIGH":     2,
		"CASE_PRIORITY_P3_MEDIUM":   3,
		"CASE_PRIORITY_P4_LOW":      4,
	}
)

func (x CasePriority) Enum() *CasePriority {
	p := new(CasePriority)
	*p = x
	return p
}

func (x CasePriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CasePriority) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_case_proto_enumTypes[1].Descriptor()
}

func (CasePriority) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_case_proto_enumTypes[1]
}

func (x CasePriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CasePriority.Descriptor instead.
func (CasePriority) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_case_proto_rawDescGZIP(), []int{1}
}

// CaseDisposition records the investigation outcome separately from status.
type CaseDisposition int32

const (
	CaseDisposition_CASE_DISPOSITION_UNSPECIFIED        CaseDisposition = 0
	CaseDisposition_CASE_DISPOSITION_UNDETERMINED       CaseDisposition = 1
	CaseDisposition_CASE_DISPOSITION_CONFIRMED_INCIDENT CaseDisposition = 2
	CaseDisposition_CASE_DISPOSITION_BENIGN_ACTIVITY    CaseDisposition = 3
	CaseDisposition_CASE_DISPOSITION_FALSE_POSITIVE     CaseDisposition = 4
	CaseDisposition_CASE_DISPOSITION_DUPLICATE          CaseDisposition = 5
	CaseDisposition_CASE_DISPOSITION_TEST               CaseDisposition = 6
	CaseDisposition_CASE_DISPOSITION_OTHER              CaseDisposition = 7
)

// Enum value maps for CaseDisposition.
var (
	CaseDisposition_name = map[int32]string{
		0: "CASE_DISPOSITION_UNSPECIFIED",
		1: "CASE_DISPOSITION_UNDETERMINED",
		2: "CASE_DISPOSITION_CONFIRMED_INCIDENT",
		3: "CASE_DISPOSITION_BENIGN_ACTIVITY",
		4: "CASE_DISPOSITION_FALSE_POSITIVE",
		5: "CASE_DISPOSITION_DUPLICATE",
		6: "CASE_DISPOSITION_TEST",
		7: "CASE_DISPOSITION_OTHER",
	}
	CaseDisposition_value = map[string]int32{
		"CASE_DISPOSITION_UNSPECIFIED":        0,
		"CASE_DISPOSITION_UNDETERMINED":       1,
		"CASE_DISPOSITION_CONFIRMED_INCIDENT": 2,
		"CASE_DISPOSITION_BENIGN_ACTIVITY":    3,
		"CASE_DISPOSITION_FALSE_POSITIVE":     4,
		"CASE_DISPOSITION_DUPLICATE":          5,
		"CASE_DISPOSITION_TEST":               6,
		"CASE_DISPOSITION_OTHER":              7,
	}
)

func (x CaseDisposition) Enum() *CaseDisposition {
	p := new(CaseDisposition)
	*p = x
	return p
}

func (x CaseDisposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaseDisposition) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_case_proto_enumTypes[2].Descriptor()
}

func (CaseDisposition) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_case_proto_enumTypes[2]
}

func (x CaseDisposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaseDisposition.Descriptor instead.
func (CaseDisposition) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_case_proto_rawDescGZIP(), []int{2}
}

// Case is the managed investigation workspace; relationships remain explicit.
type Case struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CaseNumber    string                 `protobuf:"bytes,3,opt,name=case_number,json=caseNumber,proto3" json:"case_number,omitempty"`
	Status        CaseStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=cerbero.contracts.v1.CaseStatus" json:"status,omitempty"`
	Priority      CasePriority           `protobuf:"varint,5,opt,name=priority,proto3,enum=cerbero.contracts.v1.CasePriority" json:"priority,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	OwnerUserId   *string                `protobuf:"bytes,8,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	Disposition   CaseDisposition        `protobuf:"varint,13,opt,name=disposition,proto3,enum=cerbero.contracts.v1.CaseDisposition" json:"disposition,omitempty"`
	ClosureReason *string                `protobuf:"bytes,14,opt,name=closure_reason,json=closureReason,proto3,oneof" json:"closure_reason,omitempty"`
	Version       uint64                 `protobuf:"varint,15,opt,name=version,proto3" json:"version,omitempty"`
	IncidentIds   []string               `protobuf:"bytes,16,rep,name=incident_ids,json=incidentIds,proto3" json:"incident_ids,omitempty"`
	FindingIds    []string               `protobuf:"bytes,17,rep,name=finding_ids,json=findingIds,proto3" json:"finding_ids,omitempty"`
	EntityIds     []string               `protobuf:"bytes,18,rep,name=entity_ids,json=entityIds,proto3" json:"entity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Case) Reset() {
	*x = Case{}
	mi := &file_cerbero_contracts_v1_case_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_case_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_case_proto_rawDescGZIP(), []int{0}
}

func (x *Case) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *Case) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Case) GetCaseNumber() string {
	if x != nil {
		return x.CaseNumber
	}
	return ""
}

func (x *Case) GetStatus() CaseStatus {
	if x != nil {
		return x.Status
	}
	return CaseStatus_CASE_STATUS_UNSPECIFIED
}

func (x *Case) GetPriority() CasePriority {
	if x != nil {
		return x.Priority
	}
	return CasePriority_CASE_PRIORITY_UNSPECIFIED
}

func (x *Case) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Case) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Case) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *Case) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Case) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Case) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Case) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *Case) GetDisposition() CaseDisposition {
	if x != nil {
		return x.Disposition
	}
	return CaseDisposition_CASE_DISPOSITION_UNSPECIFIED
}

func (x *Case) GetClosureReason() string {
	if x != nil && x.ClosureReason != nil {
		return *x.ClosureReason
	}
	return ""
}

func (x *Case) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Case) GetIncidentIds() []string {
	if x != nil {
		return x.IncidentIds
	}
	return nil
}

func (x *Case) GetFindingIds() []string {
	if x != nil {
		return x.FindingIds
	}
	return nil
}

func (x *Case) GetEntityIds() []string {
	if x != nil {
		return x.EntityIds
	}
	return nil
}

var File_cerbero_contracts_v1_case_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_case_proto_rawDesc = "" +
	"\n" +
	"\x1fcerbero/contracts/v1/case.proto\x12\x14cerbero.contracts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x06\n" +
	"\x04Case\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vcase_number\x18\x03 \x01(\tR\n" +
	"caseNumber\x128\n" +
	"\x06status\x18\x04 \x01(\x0e2 .cerbero.contracts.v1.CaseStatusR\x06status\x12>\n" +
	"\bpriority\x18\x05 \x01(\x0e2\".cerbero.contracts.v1.CasePriorityR\bpriority\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12'\n" +
	"\rowner_user_id\x18\b \x01(\tH\x00R\vownerUserId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\tclosed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12G\n" +
	"\vdisposition\x18\r \x01(\x0e2%.cerbero.contracts.v1.CaseDispositionR\vdisposition\x12*\n" +
	"\x0eclosure_reason\x18\x0e \x01(\tH\x01R\rclosureReason\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\x0f \x01(\x04R\aversion\x12!\n" +
	"\fincident_ids\x18\x10 \x03(\tR\vincidentIds\x12\x1f\n" +
	"\vfinding_ids\x18\x11 \x03(\tR\n" +
	"findingIds\x12\x1d\n" +
	"\n" +
	"entity_ids\x18\x12 \x03(\tR\tentityIdsB\x10\n" +
	"\x0e_owner_user_idB\x11\n" +
	"\x0f_closure_reason*\xdb\x01\n" +
	"\n" +
	"CaseStatus\x12\x1b\n" +
	"\x17CASE_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CASE_STATUS_OPEN\x10\x01\x12\x16\n" +
	"\x12CASE_STATUS_TRIAGE\x10\x02\x12\x1d\n" +
	"\x19CASE_STATUS_INVESTIGATING\x10\x03\x12\x17\n" +
	"\x13CASE_STATUS_ON_HOLD\x10\x04\x12\x18\n" +
	"\x14CASE_STATUS_RESPONSE\x10\x05\x12\x18\n" +
	"\x14CASE_STATUS_RESOLVED\x10\x06\x12\x16\n" +
	"\x12CASE_STATUS_CLOSED\x10\a*\x9e\x01\n" +
	"\fCasePriority\x12\x1d\n" +
	"\x19CASE_PRIORITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CASE_PRIORITY_P1_CRITICAL\x10\x01\x12\x19\n" +
	"\x15CASE_PRIORITY_P2_HIGH\x10\x02\x12\x1b\n" +
	"\x17CASE_PRIORITY_P3_MEDIUM\x10\x03\x12\x18\n" +
	"\x14CASE_PRIORITY_P4_LOW\x10\x04*\xa1\x02\n" +
	"\x0fCaseDisposition\x12 \n" +
	"\x1cCASE_DISPOSITION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCASE_DISPOSITION_UNDETERMINED\x10\x01\x12'\n" +
	"#CASE_DISPOSITION_CONFIRMED_INCIDENT\x10\x02\x12$\n" +
	" CASE_DISPOSITION_BENIGN_ACTIVITY\x10\x03\x12#\n" +
	"\x1fCASE_DISPOSITION_FALSE_POSITIVE\x10\x04\x12\x1e\n" +
	"\x1aCASE_DISPOSITION_DUPLICATE\x10\x05\x12\x19\n" +
	"\x15CASE_DISPOSITION_TEST\x10\x06\x12\x1a\n" +
	"\x16CASE_DISPOSITION_OTHER\x10\aB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_case_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_case_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_case_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_case_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_case_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_case_proto_rawDesc), len(file_cerbero_contracts_v1_case_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_case_proto_rawDescData
}

var file_cerbero_contracts_v1_case_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cerbero_contracts_v1_case_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbero_contracts_v1_case_proto_goTypes = []any{
	(CaseStatus)(0),               // 0: cerbero.contracts.v1.CaseStatus
	(CasePriority)(0),             // 1: cerbero.contracts.v1.CasePriority
	(CaseDisposition)(0),          // 2: cerbero.contracts.v1.CaseDisposition
	(*Case)(nil),                  // 3: cerbero.contracts.v1.Case
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_cerbero_contracts_v1_case_proto_depIdxs = []int32{
	0, // 0: cerbero.contracts.v1.Case.status:type_name -> cerbero.contracts.v1.CaseStatus
	1, // 1: cerbero.contracts.v1.Case.priority:type_name -> cerbero.contracts.v1.CasePriority
	4, // 2: cerbero.contracts.v1.Case.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: cerbero.contracts.v1.Case.updated_at:type_name -> google.protobuf.Timestamp
	4, // 4: cerbero.contracts.v1.Case.closed_at:type_name -> google.protobuf.Timestamp
	2, // 5: cerbero.contracts.v1.Case.disposition:type_name -> cerbero.contracts.v1.CaseDisposition
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_case_proto_init() }
func file_cerbero_contracts_v1_case_proto_init() {
	if File_cerbero_contracts_v1_case_proto != nil {
		return
	}
	file_cerbero_contracts_v1_case_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_case_proto_rawDesc), len(file_cerbero_contracts_v1_case_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_case_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_case_proto_depIdxs,
		EnumInfos:         file_cerbero_contracts_v1_case_proto_enumTypes,
		MessageInfos:      file_cerbero_contracts_v1_case_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_case_proto = out.File
	file_cerbero_contracts_v1_case_proto_goTypes = nil
	file_cerbero_contracts_v1_case_proto_depIdxs = nil
}
