// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/common.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IntegrityStatus describes the evidence-integrity assessment of a RawEvent.
type IntegrityStatus int32

const (
	IntegrityStatus_INTEGRITY_STATUS_UNSPECIFIED IntegrityStatus = 0
	IntegrityStatus_INTEGRITY_UNVERIFIED         IntegrityStatus = 1
	IntegrityStatus_INTEGRITY_VALID              IntegrityStatus = 2
	IntegrityStatus_INTEGRITY_INVALID            IntegrityStatus = 3
)

// Enum value maps for IntegrityStatus.
var (
	IntegrityStatus_name = map[int32]string{
		0: "INTEGRITY_STATUS_UNSPECIFIED",
		1: "INTEGRITY_UNVERIFIED",
		2: "INTEGRITY_VALID",
		3: "INTEGRITY_INVALID",
	}
	IntegrityStatus_value = map[string]int32{
		"INTEGRITY_STATUS_UNSPECIFIED": 0,
		"INTEGRITY_UNVERIFIED":         1,
		"INTEGRITY_VALID":              2,
		"INTEGRITY_INVALID":            3,
	}
)

func (x IntegrityStatus) Enum() *IntegrityStatus {
	p := new(IntegrityStatus)
	*p = x
	return p
}

func (x IntegrityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_common_proto_enumTypes[0].Descriptor()
}

func (IntegrityStatus) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_common_proto_enumTypes[0]
}

func (x IntegrityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrityStatus.Descriptor instead.
func (IntegrityStatus) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_common_proto_rawDescGZIP(), []int{0}
}

// NormalizationStatus describes the outcome represented by a normalized derivation.
type NormalizationStatus int32

const (
	NormalizationStatus_NORMALIZATION_STATUS_UNSPECIFIED NormalizationStatus = 0
	NormalizationStatus_NORMALIZATION_STATUS_SUCCESS     NormalizationStatus = 1
	NormalizationStatus_NORMALIZATION_STATUS_PARTIAL     NormalizationStatus = 2
	NormalizationStatus_NORMALIZATION_STATUS_FAILED      NormalizationStatus = 3
)

// Enum value maps for NormalizationStatus.
var (
	NormalizationStatus_name = map[int32]string{
		0: "NORMALIZATION_STATUS_UNSPECIFIED",
		1: "NORMALIZATION_STATUS_SUCCESS",
		2: "NORMALIZATION_STATUS_PARTIAL",
		3: "NORMALIZATION_STATUS_FAILED",
	}
	NormalizationStatus_value = map[string]int32{
		"NORMALIZATION_STATUS_UNSPECIFIED": 0,
		"NORMALIZATION_STATUS_SUCCESS":     1,
		"NORMALIZATION_STATUS_PARTIAL":     2,
		"NORMALIZATION_STATUS_FAILED":      3,
	}
)

func (x NormalizationStatus) Enum() *NormalizationStatus {
	p := new(NormalizationStatus)
	*p = x
	return p
}

func (x NormalizationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NormalizationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_common_proto_enumTypes[1].Descriptor()
}

func (NormalizationStatus) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_common_proto_enumTypes[1]
}

func (x NormalizationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NormalizationStatus.Descriptor instead.
func (NormalizationStatus) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_common_proto_rawDescGZIP(), []int{1}
}

// TransformationStatus records whether a transformation completed successfully or failed.
type TransformationStatus int32

const (
	TransformationStatus_TRANSFORMATION_STATUS_UNSPECIFIED TransformationStatus = 0
	TransformationStatus_TRANSFORMATION_STATUS_SUCCESS     TransformationStatus = 1
	TransformationStatus_TRANSFORMATION_STATUS_FAILED      TransformationStatus = 2
)

// Enum value maps for TransformationStatus.
var (
	TransformationStatus_name = map[int32]string{
		0: "TRANSFORMATION_STATUS_UNSPECIFIED",
		1: "TRANSFORMATION_STATUS_SUCCESS",
		2: "TRANSFORMATION_STATUS_FAILED",
	}
	TransformationStatus_value = map[string]int32{
		"TRANSFORMATION_STATUS_UNSPECIFIED": 0,
		"TRANSFORMATION_STATUS_SUCCESS":     1,
		"TRANSFORMATION_STATUS_FAILED":      2,
	}
)

func (x TransformationStatus) Enum() *TransformationStatus {
	p := new(TransformationStatus)
	*p = x
	return p
}

func (x TransformationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransformationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_common_proto_enumTypes[2].Descriptor()
}

func (TransformationStatus) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_common_proto_enumTypes[2]
}

func (x TransformationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransformationStatus.Descriptor instead.
func (TransformationStatus) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_common_proto_rawDescGZIP(), []int{2}
}

// ExecutionMode separates real-time processing, replay, and isolated test execution.
type ExecutionMode int32

const (
	ExecutionMode_EXECUTION_MODE_UNSPECIFIED ExecutionMode = 0
	ExecutionMode_EXECUTION_MODE_LIVE        ExecutionMode = 1
	ExecutionMode_EXECUTION_MODE_REPLAY      ExecutionMode = 2
	ExecutionMode_EXECUTION_MODE_TEST        ExecutionMode = 3
)

// Enum value maps for ExecutionMode.
var (
	ExecutionMode_name = map[int32]string{
		0: "EXECUTION_MODE_UNSPECIFIED",
		1: "EXECUTION_MODE_LIVE",
		2: "EXECUTION_MODE_REPLAY",
		3: "EXECUTION_MODE_TEST",
	}
	ExecutionMode_value = map[string]int32{
		"EXECUTION_MODE_UNSPECIFIED": 0,
		"EXECUTION_MODE_LIVE":        1,
		"EXECUTION_MODE_REPLAY":      2,
		"EXECUTION_MODE_TEST":        3,
	}
)

func (x ExecutionMode) Enum() *ExecutionMode {
	p := new(ExecutionMode)
	*p = x
	return p
}

func (x ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_common_proto_enumTypes[3].Descriptor()
}

func (ExecutionMode) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_common_proto_enumTypes[3]
}

func (x ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMode.Descriptor instead.
func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_common_proto_rawDescGZIP(), []int{3}
}

// Producer identifies the concrete CERBERO component instance that emitted a message.
type Producer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Component        string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	ComponentVersion string                 `protobuf:"bytes,2,opt,name=component_version,json=componentVersion,proto3" json:"component_version,omitempty"`
	InstanceId       string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Producer) Reset() {
	*x = Producer{}
	mi := &file_cerbero_contracts_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producer) ProtoMessage() {}

func (x *Producer) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producer.ProtoReflect.Descriptor instead.
func (*Producer) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *Producer) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Producer) GetComponentVersion() string {
	if x != nil {
		return x.ComponentVersion
	}
	return ""
}

func (x *Producer) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

var File_cerbero_contracts_v1_common_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_common_proto_rawDesc = "" +
	"\n" +
	"!cerbero/contracts/v1/common.proto\x12\x14cerbero.contracts.v1\"v\n" +
	"\bProducer\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12+\n" +
	"\x11component_version\x18\x02 \x01(\tR\x10componentVersion\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId*y\n" +
	"\x0fIntegrityStatus\x12 \n" +
	"\x1cINTEGRITY_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INTEGRITY_UNVERIFIED\x10\x01\x12\x13\n" +
	"\x0fINTEGRITY_VALID\x10\x02\x12\x15\n" +
	"\x11INTEGRITY_INVALID\x10\x03*\xa0\x01\n" +
	"\x13NormalizationStatus\x12$\n" +
	" NORMALIZATION_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cNORMALIZATION_STATUS_SUCCESS\x10\x01\x12 \n" +
	"\x1cNORMALIZATION_STATUS_PARTIAL\x10\x02\x12\x1f\n" +
	"\x1bNORMALIZATION_STATUS_FAILED\x10\x03*\x82\x01\n" +
	"\x14TransformationStatus\x12%\n" +
	"!TRANSFORMATION_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTRANSFORMATION_STATUS_SUCCESS\x10\x01\x12 \n" +
	"\x1cTRANSFORMATION_STATUS_FAILED\x10\x02*|\n" +
	"\rExecutionMode\x12\x1e\n" +
	"\x1aEXECUTION_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXECUTION_MODE_LIVE\x10\x01\x12\x19\n" +
	"\x15EXECUTION_MODE_REPLAY\x10\x02\x12\x17\n" +
	"\x13EXECUTION_MODE_TEST\x10\x03B4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_common_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_common_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_common_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_common_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_common_proto_rawDesc), len(file_cerbero_contracts_v1_common_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_common_proto_rawDescData
}

var file_cerbero_contracts_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cerbero_contracts_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbero_contracts_v1_common_proto_goTypes = []any{
	(IntegrityStatus)(0),      // 0: cerbero.contracts.v1.IntegrityStatus
	(NormalizationStatus)(0),  // 1: cerbero.contracts.v1.NormalizationStatus
	(TransformationStatus)(0), // 2: cerbero.contracts.v1.TransformationStatus
	(ExecutionMode)(0),        // 3: cerbero.contracts.v1.ExecutionMode
	(*Producer)(nil),          // 4: cerbero.contracts.v1.Producer
}
var file_cerbero_contracts_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_common_proto_init() }
func file_cerbero_contracts_v1_common_proto_init() {
	if File_cerbero_contracts_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_common_proto_rawDesc), len(file_cerbero_contracts_v1_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_common_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_common_proto_depIdxs,
		EnumInfos:         file_cerbero_contracts_v1_common_proto_enumTypes,
		MessageInfos:      file_cerbero_contracts_v1_common_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_common_proto = out.File
	file_cerbero_contracts_v1_common_proto_goTypes = nil
	file_cerbero_contracts_v1_common_proto_depIdxs = nil
}
