// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/entity.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntityType identifies the initial canonical entity families.
type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED EntityType = 0
	EntityType_ENTITY_TYPE_HOST        EntityType = 1
	EntityType_ENTITY_TYPE_USER        EntityType = 2
	EntityType_ENTITY_TYPE_ACCOUNT     EntityType = 3
	EntityType_ENTITY_TYPE_IP          EntityType = 4
	EntityType_ENTITY_TYPE_PROCESS     EntityType = 5
	EntityType_ENTITY_TYPE_FILE        EntityType = 6
	EntityType_ENTITY_TYPE_CONTAINER   EntityType = 7
	EntityType_ENTITY_TYPE_SERVICE     EntityType = 8
	EntityType_ENTITY_TYPE_APPLICATION EntityType = 9
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "ENTITY_TYPE_HOST",
		2: "ENTITY_TYPE_USER",
		3: "ENTITY_TYPE_ACCOUNT",
		4: "ENTITY_TYPE_IP",
		5: "ENTITY_TYPE_PROCESS",
		6: "ENTITY_TYPE_FILE",
		7: "ENTITY_TYPE_CONTAINER",
		8: "ENTITY_TYPE_SERVICE",
		9: "ENTITY_TYPE_APPLICATION",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED": 0,
		"ENTITY_TYPE_HOST":        1,
		"ENTITY_TYPE_USER":        2,
		"ENTITY_TYPE_ACCOUNT":     3,
		"ENTITY_TYPE_IP":          4,
		"ENTITY_TYPE_PROCESS":     5,
		"ENTITY_TYPE_FILE":        6,
		"ENTITY_TYPE_CONTAINER":   7,
		"ENTITY_TYPE_SERVICE":     8,
		"ENTITY_TYPE_APPLICATION": 9,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_entity_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_entity_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_entity_proto_rawDescGZIP(), []int{0}
}

// FindingEntityRole records how an Entity participates in a Finding.
type FindingEntityRole int32

const (
	FindingEntityRole_FINDING_ENTITY_ROLE_UNSPECIFIED FindingEntityRole = 0
	FindingEntityRole_FINDING_ENTITY_ROLE_SUBJECT     FindingEntityRole = 1
	FindingEntityRole_FINDING_ENTITY_ROLE_SOURCE      FindingEntityRole = 2
	FindingEntityRole_FINDING_ENTITY_ROLE_DESTINATION FindingEntityRole = 3
	FindingEntityRole_FINDING_ENTITY_ROLE_ACTOR       FindingEntityRole = 4
	FindingEntityRole_FINDING_ENTITY_ROLE_TARGET      FindingEntityRole = 5
	FindingEntityRole_FINDING_ENTITY_ROLE_AFFECTED    FindingEntityRole = 6
	FindingEntityRole_FINDING_ENTITY_ROLE_RELATED     FindingEntityRole = 7
)

// Enum value maps for FindingEntityRole.
var (
	FindingEntityRole_name = map[int32]string{
		0: "FINDING_ENTITY_ROLE_UNSPECIFIED",
		1: "FINDING_ENTITY_ROLE_SUBJECT",
		2: "FINDING_ENTITY_ROLE_SOURCE",
		3: "FINDING_ENTITY_ROLE_DESTINATION",
		4: "FINDING_ENTITY_ROLE_ACTOR",
		5: "FINDING_ENTITY_ROLE_TARGET",
		6: "FINDING_ENTITY_ROLE_AFFECTED",
		7: "FINDING_ENTITY_ROLE_RELATED",
	}
	FindingEntityRole_value = map[string]int32{
		"FINDING_ENTITY_ROLE_UNSPECIFIED": 0,
		"FINDING_ENTITY_ROLE_SUBJECT":     1,
		"FINDING_ENTITY_ROLE_SOURCE":      2,
		"FINDING_ENTITY_ROLE_DESTINATION": 3,
		"FINDING_ENTITY_ROLE_ACTOR":       4,
		"FINDING_ENTITY_ROLE_TARGET":      5,
		"FINDING_ENTITY_ROLE_AFFECTED":    6,
		"FINDING_ENTITY_ROLE_RELATED":     7,
	}
)

func (x FindingEntityRole) Enum() *FindingEntityRole {
	p := new(FindingEntityRole)
	*p = x
	return p
}

func (x FindingEntityRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingEntityRole) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_entity_proto_enumTypes[1].Descriptor()
}

func (FindingEntityRole) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_entity_proto_enumTypes[1]
}

func (x FindingEntityRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingEntityRole.Descriptor instead.
func (FindingEntityRole) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_entity_proto_rawDescGZIP(), []int{1}
}

// Entity is the canonical tenant-scoped identity used by the risk ledger.
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EntityType    EntityType             `protobuf:"varint,3,opt,name=entity_type,json=entityType,proto3,enum=cerbero.contracts.v1.EntityType" json:"entity_type,omitempty"`
	CanonicalKey  string                 `protobuf:"bytes,4,opt,name=canonical_key,json=canonicalKey,proto3" json:"canonical_key,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Criticality   *string                `protobuf:"bytes,7,opt,name=criticality,proto3,oneof" json:"criticality,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,8,opt,name=attributes,proto3" json:"attributes,omitempty"`
	RiskScore     string                 `protobuf:"bytes,9,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_cerbero_contracts_v1_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Entity) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Entity) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_TYPE_UNSPECIFIED
}

func (x *Entity) GetCanonicalKey() string {
	if x != nil {
		return x.CanonicalKey
	}
	return ""
}

func (x *Entity) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Entity) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Entity) GetCriticality() string {
	if x != nil && x.Criticality != nil {
		return *x.Criticality
	}
	return ""
}

func (x *Entity) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Entity) GetRiskScore() string {
	if x != nil {
		return x.RiskScore
	}
	return ""
}

// FindingEntity preserves an explicit analytical relationship without destructive identity merging.
type FindingEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FindingId     string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Role          FindingEntityRole      `protobuf:"varint,3,opt,name=role,proto3,enum=cerbero.contracts.v1.FindingEntityRole" json:"role,omitempty"`
	Confidence    *string                `protobuf:"bytes,4,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingEntity) Reset() {
	*x = FindingEntity{}
	mi := &file_cerbero_contracts_v1_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingEntity) ProtoMessage() {}

func (x *FindingEntity) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingEntity.ProtoReflect.Descriptor instead.
func (*FindingEntity) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_entity_proto_rawDescGZIP(), []int{1}
}

func (x *FindingEntity) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *FindingEntity) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *FindingEntity) GetRole() FindingEntityRole {
	if x != nil {
		return x.Role
	}
	return FindingEntityRole_FINDING_ENTITY_ROLE_UNSPECIFIED
}

func (x *FindingEntity) GetConfidence() string {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return ""
}

// RiskContribution is one reconstructible ledger entry. It does not freeze the aggregate risk formula.
type RiskContribution struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContributionId string                 `protobuf:"bytes,1,opt,name=contribution_id,json=contributionId,proto3" json:"contribution_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EntityId       string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	FindingId      string                 `protobuf:"bytes,4,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	Amount         string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Severity       string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence     *string                `protobuf:"bytes,7,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Reason         string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	RuleId         *string                `protobuf:"bytes,9,opt,name=rule_id,json=ruleId,proto3,oneof" json:"rule_id,omitempty"`
	RuleVersion    *string                `protobuf:"bytes,10,opt,name=rule_version,json=ruleVersion,proto3,oneof" json:"rule_version,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RiskContribution) Reset() {
	*x = RiskContribution{}
	mi := &file_cerbero_contracts_v1_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskContribution) ProtoMessage() {}

func (x *RiskContribution) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskContribution.ProtoReflect.Descriptor instead.
func (*RiskContribution) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_entity_proto_rawDescGZIP(), []int{2}
}

func (x *RiskContribution) GetContributionId() string {
	if x != nil {
		return x.ContributionId
	}
	return ""
}

func (x *RiskContribution) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RiskContribution) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *RiskContribution) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *RiskContribution) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RiskContribution) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *RiskContribution) GetConfidence() string {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return ""
}

func (x *RiskContribution) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RiskContribution) GetRuleId() string {
	if x != nil && x.RuleId != nil {
		return *x.RuleId
	}
	return ""
}

func (x *RiskContribution) GetRuleVersion() string {
	if x != nil && x.RuleVersion != nil {
		return *x.RuleVersion
	}
	return ""
}

func (x *RiskContribution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RiskContribution) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_cerbero_contracts_v1_entity_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_entity_proto_rawDesc = "" +
	"\n" +
	"!cerbero/contracts/v1/entity.proto\x12\x14cerbero.contracts.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x03\n" +
	"\x06Entity\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12A\n" +
	"\ventity_type\x18\x03 \x01(\x0e2 .cerbero.contracts.v1.EntityTypeR\n" +
	"entityType\x12#\n" +
	"\rcanonical_key\x18\x04 \x01(\tR\fcanonicalKey\x129\n" +
	"\n" +
	"first_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12%\n" +
	"\vcriticality\x18\a \x01(\tH\x00R\vcriticality\x88\x01\x01\x127\n" +
	"\n" +
	"attributes\x18\b \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"risk_score\x18\t \x01(\tR\triskScoreB\x0e\n" +
	"\f_criticality\"\xbc\x01\n" +
	"\rFindingEntity\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12;\n" +
	"\x04role\x18\x03 \x01(\x0e2'.cerbero.contracts.v1.FindingEntityRoleR\x04role\x12#\n" +
	"\n" +
	"confidence\x18\x04 \x01(\tH\x00R\n" +
	"confidence\x88\x01\x01B\r\n" +
	"\v_confidence\"\xed\x03\n" +
	"\x10RiskContribution\x12'\n" +
	"\x0fcontribution_id\x18\x01 \x01(\tR\x0econtributionId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x04 \x01(\tR\tfindingId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12#\n" +
	"\n" +
	"confidence\x18\a \x01(\tH\x00R\n" +
	"confidence\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1c\n" +
	"\arule_id\x18\t \x01(\tH\x01R\x06ruleId\x88\x01\x01\x12&\n" +
	"\frule_version\x18\n" +
	" \x01(\tH\x02R\vruleVersion\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB\r\n" +
	"\v_confidenceB\n" +
	"\n" +
	"\b_rule_idB\x0f\n" +
	"\r_rule_version*\x82\x02\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ENTITY_TYPE_HOST\x10\x01\x12\x14\n" +
	"\x10ENTITY_TYPE_USER\x10\x02\x12\x17\n" +
	"\x13ENTITY_TYPE_ACCOUNT\x10\x03\x12\x12\n" +
	"\x0eENTITY_TYPE_IP\x10\x04\x12\x17\n" +
	"\x13ENTITY_TYPE_PROCESS\x10\x05\x12\x14\n" +
	"\x10ENTITY_TYPE_FILE\x10\x06\x12\x19\n" +
	"\x15ENTITY_TYPE_CONTAINER\x10\a\x12\x17\n" +
	"\x13ENTITY_TYPE_SERVICE\x10\b\x12\x1b\n" +
	"\x17ENTITY_TYPE_APPLICATION\x10\t*\xa0\x02\n" +
	"\x11FindingEntityRole\x12#\n" +
	"\x1fFINDING_ENTITY_ROLE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bFINDING_ENTITY_ROLE_SUBJECT\x10\x01\x12\x1e\n" +
	"\x1aFINDING_ENTITY_ROLE_SOURCE\x10\x02\x12#\n" +
	"\x1fFINDING_ENTITY_ROLE_DESTINATION\x10\x03\x12\x1d\n" +
	"\x19FINDING_ENTITY_ROLE_ACTOR\x10\x04\x12\x1e\n" +
	"\x1aFINDING_ENTITY_ROLE_TARGET\x10\x05\x12 \n" +
	"\x1cFINDING_ENTITY_ROLE_AFFECTED\x10\x06\x12\x1f\n" +
	"\x1bFINDING_ENTITY_ROLE_RELATED\x10\aB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_entity_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_entity_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_entity_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_entity_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_entity_proto_rawDesc), len(file_cerbero_contracts_v1_entity_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_entity_proto_rawDescData
}

var file_cerbero_contracts_v1_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cerbero_contracts_v1_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cerbero_contracts_v1_entity_proto_goTypes = []any{
	(EntityType)(0),               // 0: cerbero.contracts.v1.EntityType
	(FindingEntityRole)(0),        // 1: cerbero.contracts.v1.FindingEntityRole
	(*Entity)(nil),                // 2: cerbero.contracts.v1.Entity
	(*FindingEntity)(nil),         // 3: cerbero.contracts.v1.FindingEntity
	(*RiskContribution)(nil),      // 4: cerbero.contracts.v1.RiskContribution
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 6: google.protobuf.Struct
}
var file_cerbero_contracts_v1_entity_proto_depIdxs = []int32{
	0, // 0: cerbero.contracts.v1.Entity.entity_type:type_name -> cerbero.contracts.v1.EntityType
	5, // 1: cerbero.contracts.v1.Entity.first_seen:type_name -> google.protobuf.Timestamp
	5, // 2: cerbero.contracts.v1.Entity.last_seen:type_name -> google.protobuf.Timestamp
	6, // 3: cerbero.contracts.v1.Entity.attributes:type_name -> google.protobuf.Struct
	1, // 4: cerbero.contracts.v1.FindingEntity.role:type_name -> cerbero.contracts.v1.FindingEntityRole
	5, // 5: cerbero.contracts.v1.RiskContribution.created_at:type_name -> google.protobuf.Timestamp
	5, // 6: cerbero.contracts.v1.RiskContribution.expires_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_entity_proto_init() }
func file_cerbero_contracts_v1_entity_proto_init() {
	if File_cerbero_contracts_v1_entity_proto != nil {
		return
	}
	file_cerbero_contracts_v1_entity_proto_msgTypes[0].OneofWrappers = []any{}
	file_cerbero_contracts_v1_entity_proto_msgTypes[1].OneofWrappers = []any{}
	file_cerbero_contracts_v1_entity_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_entity_proto_rawDesc), len(file_cerbero_contracts_v1_entity_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_entity_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_entity_proto_depIdxs,
		EnumInfos:         file_cerbero_contracts_v1_entity_proto_enumTypes,
		MessageInfos:      file_cerbero_contracts_v1_entity_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_entity_proto = out.File
	file_cerbero_contracts_v1_entity_proto_goTypes = nil
	file_cerbero_contracts_v1_entity_proto_depIdxs = nil
}
