// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/envelope.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CerberoEnvelope wraps every message published on the CERBERO event bus.
type CerberoEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractVersion string                 `protobuf:"bytes,1,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageType     string                 `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	TenantId        string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Producer        *Producer              `protobuf:"bytes,5,opt,name=producer,proto3" json:"producer,omitempty"`
	EmittedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	TraceId         string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CausationId     string                 `protobuf:"bytes,8,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,9,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	PayloadSchema   string                 `protobuf:"bytes,10,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`
	Payload         *anypb.Any             `protobuf:"bytes,11,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CerberoEnvelope) Reset() {
	*x = CerberoEnvelope{}
	mi := &file_cerbero_contracts_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CerberoEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CerberoEnvelope) ProtoMessage() {}

func (x *CerberoEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CerberoEnvelope.ProtoReflect.Descriptor instead.
func (*CerberoEnvelope) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *CerberoEnvelope) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *CerberoEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CerberoEnvelope) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *CerberoEnvelope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CerberoEnvelope) GetProducer() *Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *CerberoEnvelope) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *CerberoEnvelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CerberoEnvelope) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *CerberoEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CerberoEnvelope) GetPayloadSchema() string {
	if x != nil {
		return x.PayloadSchema
	}
	return ""
}

func (x *CerberoEnvelope) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_cerbero_contracts_v1_envelope_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"#cerbero/contracts/v1/envelope.proto\x12\x14cerbero.contracts.v1\x1a!cerbero/contracts/v1/common.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xce\x03\n" +
	"\x0fCerberoEnvelope\x12)\n" +
	"\x10contract_version\x18\x01 \x01(\tR\x0fcontractVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12:\n" +
	"\bproducer\x18\x05 \x01(\v2\x1e.cerbero.contracts.v1.ProducerR\bproducer\x129\n" +
	"\n" +
	"emitted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12!\n" +
	"\fcausation_id\x18\b \x01(\tR\vcausationId\x12%\n" +
	"\x0ecorrelation_id\x18\t \x01(\tR\rcorrelationId\x12%\n" +
	"\x0epayload_schema\x18\n" +
	" \x01(\tR\rpayloadSchema\x12.\n" +
	"\apayload\x18\v \x01(\v2\x14.google.protobuf.AnyR\apayloadB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_envelope_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_envelope_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_envelope_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_envelope_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_envelope_proto_rawDesc), len(file_cerbero_contracts_v1_envelope_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_envelope_proto_rawDescData
}

var file_cerbero_contracts_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbero_contracts_v1_envelope_proto_goTypes = []any{
	(*CerberoEnvelope)(nil),       // 0: cerbero.contracts.v1.CerberoEnvelope
	(*Producer)(nil),              // 1: cerbero.contracts.v1.Producer
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 3: google.protobuf.Any
}
var file_cerbero_contracts_v1_envelope_proto_depIdxs = []int32{
	1, // 0: cerbero.contracts.v1.CerberoEnvelope.producer:type_name -> cerbero.contracts.v1.Producer
	2, // 1: cerbero.contracts.v1.CerberoEnvelope.emitted_at:type_name -> google.protobuf.Timestamp
	3, // 2: cerbero.contracts.v1.CerberoEnvelope.payload:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_envelope_proto_init() }
func file_cerbero_contracts_v1_envelope_proto_init() {
	if File_cerbero_contracts_v1_envelope_proto != nil {
		return
	}
	file_cerbero_contracts_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_envelope_proto_rawDesc), len(file_cerbero_contracts_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_envelope_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_envelope_proto_depIdxs,
		MessageInfos:      file_cerbero_contracts_v1_envelope_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_envelope_proto = out.File
	file_cerbero_contracts_v1_envelope_proto_goTypes = nil
	file_cerbero_contracts_v1_envelope_proto_depIdxs = nil
}
