// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/error.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCategory values are locked by CONTRACTS v1.0 and intentionally retain their exact names.
type ErrorCategory int32

const (
	ErrorCategory_ERROR_CATEGORY_UNSPECIFIED ErrorCategory = 0
	ErrorCategory_VALIDATION                 ErrorCategory = 1
	ErrorCategory_AUTHENTICATION             ErrorCategory = 2
	ErrorCategory_AUTHORIZATION              ErrorCategory = 3
	ErrorCategory_RATE_LIMIT                 ErrorCategory = 4
	ErrorCategory_CONFLICT                   ErrorCategory = 5
	ErrorCategory_PARSING                    ErrorCategory = 6
	ErrorCategory_NORMALIZATION              ErrorCategory = 7
	ErrorCategory_STORAGE                    ErrorCategory = 8
	ErrorCategory_TRANSPORT                  ErrorCategory = 9
	ErrorCategory_DEPENDENCY                 ErrorCategory = 10
	ErrorCategory_INTEGRITY                  ErrorCategory = 11
	ErrorCategory_INTERNAL                   ErrorCategory = 12
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0:  "ERROR_CATEGORY_UNSPECIFIED",
		1:  "VALIDATION",
		2:  "AUTHENTICATION",
		3:  "AUTHORIZATION",
		4:  "RATE_LIMIT",
		5:  "CONFLICT",
		6:  "PARSING",
		7:  "NORMALIZATION",
		8:  "STORAGE",
		9:  "TRANSPORT",
		10: "DEPENDENCY",
		11: "INTEGRITY",
		12: "INTERNAL",
	}
	ErrorCategory_value = map[string]int32{
		"ERROR_CATEGORY_UNSPECIFIED": 0,
		"VALIDATION":                 1,
		"AUTHENTICATION":             2,
		"AUTHORIZATION":              3,
		"RATE_LIMIT":                 4,
		"CONFLICT":                   5,
		"PARSING":                    6,
		"NORMALIZATION":              7,
		"STORAGE":                    8,
		"TRANSPORT":                  9,
		"DEPENDENCY":                 10,
		"INTEGRITY":                  11,
		"INTERNAL":                   12,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_error_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_error_proto_rawDescGZIP(), []int{0}
}

// CerberoError is the stable error shape exchanged between CERBERO services.
type CerberoError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Category      ErrorCategory          `protobuf:"varint,2,opt,name=category,proto3,enum=cerbero.contracts.v1.ErrorCategory" json:"category,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Component     string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CerberoError) Reset() {
	*x = CerberoError{}
	mi := &file_cerbero_contracts_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CerberoError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CerberoError) ProtoMessage() {}

func (x *CerberoError) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CerberoError.ProtoReflect.Descriptor instead.
func (*CerberoError) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *CerberoError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CerberoError) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_ERROR_CATEGORY_UNSPECIFIED
}

func (x *CerberoError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CerberoError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *CerberoError) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *CerberoError) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CerberoError) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_cerbero_contracts_v1_error_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_error_proto_rawDesc = "" +
	"\n" +
	" cerbero/contracts/v1/error.proto\x12\x14cerbero.contracts.v1\"\xe3\x02\n" +
	"\fCerberoError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12?\n" +
	"\bcategory\x18\x02 \x01(\x0e2#.cerbero.contracts.v1.ErrorCategoryR\bcategory\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12L\n" +
	"\bmetadata\x18\a \x03(\v20.cerbero.contracts.v1.CerberoError.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xed\x01\n" +
	"\rErrorCategory\x12\x1e\n" +
	"\x1aERROR_CATEGORY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"VALIDATION\x10\x01\x12\x12\n" +
	"\x0eAUTHENTICATION\x10\x02\x12\x11\n" +
	"\rAUTHORIZATION\x10\x03\x12\x0e\n" +
	"\n" +
	"RATE_LIMIT\x10\x04\x12\f\n" +
	"\bCONFLICT\x10\x05\x12\v\n" +
	"\aPARSING\x10\x06\x12\x11\n" +
	"\rNORMALIZATION\x10\a\x12\v\n" +
	"\aSTORAGE\x10\b\x12\r\n" +
	"\tTRANSPORT\x10\t\x12\x0e\n" +
	"\n" +
	"DEPENDENCY\x10\n" +
	"\x12\r\n" +
	"\tINTEGRITY\x10\v\x12\f\n" +
	"\bINTERNAL\x10\fB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_error_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_error_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_error_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_error_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_error_proto_rawDesc), len(file_cerbero_contracts_v1_error_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_error_proto_rawDescData
}

var file_cerbero_contracts_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cerbero_contracts_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cerbero_contracts_v1_error_proto_goTypes = []any{
	(ErrorCategory)(0),   // 0: cerbero.contracts.v1.ErrorCategory
	(*CerberoError)(nil), // 1: cerbero.contracts.v1.CerberoError
	nil,                  // 2: cerbero.contracts.v1.CerberoError.MetadataEntry
}
var file_cerbero_contracts_v1_error_proto_depIdxs = []int32{
	0, // 0: cerbero.contracts.v1.CerberoError.category:type_name -> cerbero.contracts.v1.ErrorCategory
	2, // 1: cerbero.contracts.v1.CerberoError.metadata:type_name -> cerbero.contracts.v1.CerberoError.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_error_proto_init() }
func file_cerbero_contracts_v1_error_proto_init() {
	if File_cerbero_contracts_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_error_proto_rawDesc), len(file_cerbero_contracts_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_error_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_error_proto_depIdxs,
		EnumInfos:         file_cerbero_contracts_v1_error_proto_enumTypes,
		MessageInfos:      file_cerbero_contracts_v1_error_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_error_proto = out.File
	file_cerbero_contracts_v1_error_proto_goTypes = nil
	file_cerbero_contracts_v1_error_proto_depIdxs = nil
}
