// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/finding.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FindingType identifies why a Finding exists analytically.
type FindingType int32

const (
	FindingType_FINDING_TYPE_UNSPECIFIED FindingType = 0
	FindingType_FINDING_TYPE_DETECTION   FindingType = 1
	FindingType_FINDING_TYPE_THRESHOLD   FindingType = 2
	FindingType_FINDING_TYPE_CORRELATION FindingType = 3
	FindingType_FINDING_TYPE_ANALYTICAL  FindingType = 4
)

// Enum value maps for FindingType.
var (
	FindingType_name = map[int32]string{
		0: "FINDING_TYPE_UNSPECIFIED",
		1: "FINDING_TYPE_DETECTION",
		2: "FINDING_TYPE_THRESHOLD",
		3: "FINDING_TYPE_CORRELATION",
		4: "FINDING_TYPE_ANALYTICAL",
	}
	FindingType_value = map[string]int32{
		"FINDING_TYPE_UNSPECIFIED": 0,
		"FINDING_TYPE_DETECTION":   1,
		"FINDING_TYPE_THRESHOLD":   2,
		"FINDING_TYPE_CORRELATION": 3,
		"FINDING_TYPE_ANALYTICAL":  4,
	}
)

func (x FindingType) Enum() *FindingType {
	p := new(FindingType)
	*p = x
	return p
}

func (x FindingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingType) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_finding_proto_enumTypes[0].Descriptor()
}

func (FindingType) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_finding_proto_enumTypes[0]
}

func (x FindingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingType.Descriptor instead.
func (FindingType) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_finding_proto_rawDescGZIP(), []int{0}
}

// FindingStatus records the current analytical lifecycle state without deleting history.
type FindingStatus int32

const (
	FindingStatus_FINDING_STATUS_UNSPECIFIED  FindingStatus = 0
	FindingStatus_FINDING_STATUS_OPEN         FindingStatus = 1
	FindingStatus_FINDING_STATUS_ACKNOWLEDGED FindingStatus = 2
	FindingStatus_FINDING_STATUS_SUPPRESSED   FindingStatus = 3
	FindingStatus_FINDING_STATUS_RESOLVED     FindingStatus = 4
	FindingStatus_FINDING_STATUS_INVALIDATED  FindingStatus = 5
)

// Enum value maps for FindingStatus.
var (
	FindingStatus_name = map[int32]string{
		0: "FINDING_STATUS_UNSPECIFIED",
		1: "FINDING_STATUS_OPEN",
		2: "FINDING_STATUS_ACKNOWLEDGED",
		3: "FINDING_STATUS_SUPPRESSED",
		4: "FINDING_STATUS_RESOLVED",
		5: "FINDING_STATUS_INVALIDATED",
	}
	FindingStatus_value = map[string]int32{
		"FINDING_STATUS_UNSPECIFIED":  0,
		"FINDING_STATUS_OPEN":         1,
		"FINDING_STATUS_ACKNOWLEDGED": 2,
		"FINDING_STATUS_SUPPRESSED":   3,
		"FINDING_STATUS_RESOLVED":     4,
		"FINDING_STATUS_INVALIDATED":  5,
	}
)

func (x FindingStatus) Enum() *FindingStatus {
	p := new(FindingStatus)
	*p = x
	return p
}

func (x FindingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_finding_proto_enumTypes[1].Descriptor()
}

func (FindingStatus) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_finding_proto_enumTypes[1]
}

func (x FindingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingStatus.Descriptor instead.
func (FindingStatus) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_finding_proto_rawDescGZIP(), []int{1}
}

// FindingDisposition records analytical resolution separately from operational status.
type FindingDisposition int32

const (
	FindingDisposition_FINDING_DISPOSITION_UNSPECIFIED          FindingDisposition = 0
	FindingDisposition_FINDING_DISPOSITION_UNDETERMINED         FindingDisposition = 1
	FindingDisposition_FINDING_DISPOSITION_TRUE_POSITIVE        FindingDisposition = 2
	FindingDisposition_FINDING_DISPOSITION_BENIGN_TRUE_POSITIVE FindingDisposition = 3
	FindingDisposition_FINDING_DISPOSITION_FALSE_POSITIVE       FindingDisposition = 4
	FindingDisposition_FINDING_DISPOSITION_DUPLICATE            FindingDisposition = 5
	FindingDisposition_FINDING_DISPOSITION_TEST_ACTIVITY        FindingDisposition = 6
)

// Enum value maps for FindingDisposition.
var (
	FindingDisposition_name = map[int32]string{
		0: "FINDING_DISPOSITION_UNSPECIFIED",
		1: "FINDING_DISPOSITION_UNDETERMINED",
		2: "FINDING_DISPOSITION_TRUE_POSITIVE",
		3: "FINDING_DISPOSITION_BENIGN_TRUE_POSITIVE",
		4: "FINDING_DISPOSITION_FALSE_POSITIVE",
		5: "FINDING_DISPOSITION_DUPLICATE",
		6: "FINDING_DISPOSITION_TEST_ACTIVITY",
	}
	FindingDisposition_value = map[string]int32{
		"FINDING_DISPOSITION_UNSPECIFIED":          0,
		"FINDING_DISPOSITION_UNDETERMINED":         1,
		"FINDING_DISPOSITION_TRUE_POSITIVE":        2,
		"FINDING_DISPOSITION_BENIGN_TRUE_POSITIVE": 3,
		"FINDING_DISPOSITION_FALSE_POSITIVE":       4,
		"FINDING_DISPOSITION_DUPLICATE":            5,
		"FINDING_DISPOSITION_TEST_ACTIVITY":        6,
	}
)

func (x FindingDisposition) Enum() *FindingDisposition {
	p := new(FindingDisposition)
	*p = x
	return p
}

func (x FindingDisposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingDisposition) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_finding_proto_enumTypes[2].Descriptor()
}

func (FindingDisposition) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_finding_proto_enumTypes[2]
}

func (x FindingDisposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingDisposition.Descriptor instead.
func (FindingDisposition) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_finding_proto_rawDescGZIP(), []int{2}
}

// FindingInput preserves one explicit contributing object relation.
type FindingInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FindingId     string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	InputType     string                 `protobuf:"bytes,2,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	InputId       string                 `protobuf:"bytes,3,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	Relation      string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingInput) Reset() {
	*x = FindingInput{}
	mi := &file_cerbero_contracts_v1_finding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingInput) ProtoMessage() {}

func (x *FindingInput) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_finding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingInput.ProtoReflect.Descriptor instead.
func (*FindingInput) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_finding_proto_rawDescGZIP(), []int{0}
}

func (x *FindingInput) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *FindingInput) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *FindingInput) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *FindingInput) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

// FindingCorrelationProvenance preserves the governed correlation execution record.
type FindingCorrelationProvenance struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	CorrelationRuleId      string                    `protobuf:"bytes,1,opt,name=correlation_rule_id,json=correlationRuleId,proto3" json:"correlation_rule_id,omitempty"`
	CorrelationRuleVersion string                    `protobuf:"bytes,2,opt,name=correlation_rule_version,json=correlationRuleVersion,proto3" json:"correlation_rule_version,omitempty"`
	WindowStart            *timestamppb.Timestamp    `protobuf:"bytes,3,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd              *timestamppb.Timestamp    `protobuf:"bytes,4,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	InputIds               []string                  `protobuf:"bytes,5,rep,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`
	OutputFindingId        string                    `protobuf:"bytes,6,opt,name=output_finding_id,json=outputFindingId,proto3" json:"output_finding_id,omitempty"`
	ExecutionBackend       DetectionExecutionBackend `protobuf:"varint,7,opt,name=execution_backend,json=executionBackend,proto3,enum=cerbero.contracts.v1.DetectionExecutionBackend" json:"execution_backend,omitempty"`
	ExecutionMode          ExecutionMode             `protobuf:"varint,8,opt,name=execution_mode,json=executionMode,proto3,enum=cerbero.contracts.v1.ExecutionMode" json:"execution_mode,omitempty"`
	ConfigurationHash      string                    `protobuf:"bytes,9,opt,name=configuration_hash,json=configurationHash,proto3" json:"configuration_hash,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FindingCorrelationProvenance) Reset() {
	*x = FindingCorrelationProvenance{}
	mi := &file_cerbero_contracts_v1_finding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingCorrelationProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingCorrelationProvenance) ProtoMessage() {}

func (x *FindingCorrelationProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_finding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingCorrelationProvenance.ProtoReflect.Descriptor instead.
func (*FindingCorrelationProvenance) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_finding_proto_rawDescGZIP(), []int{1}
}

func (x *FindingCorrelationProvenance) GetCorrelationRuleId() string {
	if x != nil {
		return x.CorrelationRuleId
	}
	return ""
}

func (x *FindingCorrelationProvenance) GetCorrelationRuleVersion() string {
	if x != nil {
		return x.CorrelationRuleVersion
	}
	return ""
}

func (x *FindingCorrelationProvenance) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *FindingCorrelationProvenance) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *FindingCorrelationProvenance) GetInputIds() []string {
	if x != nil {
		return x.InputIds
	}
	return nil
}

func (x *FindingCorrelationProvenance) GetOutputFindingId() string {
	if x != nil {
		return x.OutputFindingId
	}
	return ""
}

func (x *FindingCorrelationProvenance) GetExecutionBackend() DetectionExecutionBackend {
	if x != nil {
		return x.ExecutionBackend
	}
	return DetectionExecutionBackend_DETECTION_EXECUTION_BACKEND_UNSPECIFIED
}

func (x *FindingCorrelationProvenance) GetExecutionMode() ExecutionMode {
	if x != nil {
		return x.ExecutionMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *FindingCorrelationProvenance) GetConfigurationHash() string {
	if x != nil {
		return x.ConfigurationHash
	}
	return ""
}

// Finding is the canonical v1 wire representation of an analytically relevant observation.
type Finding struct {
	state                  protoimpl.MessageState        `protogen:"open.v1"`
	FindingId              string                        `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	TenantId               string                        `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FindingType            FindingType                   `protobuf:"varint,3,opt,name=finding_type,json=findingType,proto3,enum=cerbero.contracts.v1.FindingType" json:"finding_type,omitempty"`
	Status                 FindingStatus                 `protobuf:"varint,4,opt,name=status,proto3,enum=cerbero.contracts.v1.FindingStatus" json:"status,omitempty"`
	Severity               string                        `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence             *string                       `protobuf:"bytes,6,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Title                  string                        `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                        `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	FirstSeen              *timestamppb.Timestamp        `protobuf:"bytes,9,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen               *timestamppb.Timestamp        `protobuf:"bytes,10,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	CreatedAt              *timestamppb.Timestamp        `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp        `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PrimaryRuleId          *string                       `protobuf:"bytes,13,opt,name=primary_rule_id,json=primaryRuleId,proto3,oneof" json:"primary_rule_id,omitempty"`
	PrimaryRuleVersion     *string                       `protobuf:"bytes,14,opt,name=primary_rule_version,json=primaryRuleVersion,proto3,oneof" json:"primary_rule_version,omitempty"`
	CorrelationRuleId      *string                       `protobuf:"bytes,15,opt,name=correlation_rule_id,json=correlationRuleId,proto3,oneof" json:"correlation_rule_id,omitempty"`
	CorrelationRuleVersion *string                       `protobuf:"bytes,16,opt,name=correlation_rule_version,json=correlationRuleVersion,proto3,oneof" json:"correlation_rule_version,omitempty"`
	Disposition            FindingDisposition            `protobuf:"varint,17,opt,name=disposition,proto3,enum=cerbero.contracts.v1.FindingDisposition" json:"disposition,omitempty"`
	Metadata               *structpb.Struct              `protobuf:"bytes,18,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExecutionMode          ExecutionMode                 `protobuf:"varint,19,opt,name=execution_mode,json=executionMode,proto3,enum=cerbero.contracts.v1.ExecutionMode" json:"execution_mode,omitempty"`
	Inputs                 []*FindingInput               `protobuf:"bytes,20,rep,name=inputs,proto3" json:"inputs,omitempty"`
	CorrelationProvenance  *FindingCorrelationProvenance `protobuf:"bytes,21,opt,name=correlation_provenance,json=correlationProvenance,proto3" json:"correlation_provenance,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_cerbero_contracts_v1_finding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_finding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_finding_proto_rawDescGZIP(), []int{2}
}

func (x *Finding) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *Finding) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Finding) GetFindingType() FindingType {
	if x != nil {
		return x.FindingType
	}
	return FindingType_FINDING_TYPE_UNSPECIFIED
}

func (x *Finding) GetStatus() FindingStatus {
	if x != nil {
		return x.Status
	}
	return FindingStatus_FINDING_STATUS_UNSPECIFIED
}

func (x *Finding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Finding) GetConfidence() string {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return ""
}

func (x *Finding) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Finding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Finding) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Finding) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Finding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Finding) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Finding) GetPrimaryRuleId() string {
	if x != nil && x.PrimaryRuleId != nil {
		return *x.PrimaryRuleId
	}
	return ""
}

func (x *Finding) GetPrimaryRuleVersion() string {
	if x != nil && x.PrimaryRuleVersion != nil {
		return *x.PrimaryRuleVersion
	}
	return ""
}

func (x *Finding) GetCorrelationRuleId() string {
	if x != nil && x.CorrelationRuleId != nil {
		return *x.CorrelationRuleId
	}
	return ""
}

func (x *Finding) GetCorrelationRuleVersion() string {
	if x != nil && x.CorrelationRuleVersion != nil {
		return *x.CorrelationRuleVersion
	}
	return ""
}

func (x *Finding) GetDisposition() FindingDisposition {
	if x != nil {
		return x.Disposition
	}
	return FindingDisposition_FINDING_DISPOSITION_UNSPECIFIED
}

func (x *Finding) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Finding) GetExecutionMode() ExecutionMode {
	if x != nil {
		return x.ExecutionMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *Finding) GetInputs() []*FindingInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Finding) GetCorrelationProvenance() *FindingCorrelationProvenance {
	if x != nil {
		return x.CorrelationProvenance
	}
	return nil
}

var File_cerbero_contracts_v1_finding_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_finding_proto_rawDesc = "" +
	"\n" +
	"\"cerbero/contracts/v1/finding.proto\x12\x14cerbero.contracts.v1\x1a!cerbero/contracts/v1/common.proto\x1a!cerbero/contracts/v1/signal.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x01\n" +
	"\fFindingInput\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12\x1d\n" +
	"\n" +
	"input_type\x18\x02 \x01(\tR\tinputType\x12\x19\n" +
	"\binput_id\x18\x03 \x01(\tR\ainputId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\"\xa4\x04\n" +
	"\x1cFindingCorrelationProvenance\x12.\n" +
	"\x13correlation_rule_id\x18\x01 \x01(\tR\x11correlationRuleId\x128\n" +
	"\x18correlation_rule_version\x18\x02 \x01(\tR\x16correlationRuleVersion\x12=\n" +
	"\fwindow_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\x12\x1b\n" +
	"\tinput_ids\x18\x05 \x03(\tR\binputIds\x12*\n" +
	"\x11output_finding_id\x18\x06 \x01(\tR\x0foutputFindingId\x12\\\n" +
	"\x11execution_backend\x18\a \x01(\x0e2/.cerbero.contracts.v1.DetectionExecutionBackendR\x10executionBackend\x12J\n" +
	"\x0eexecution_mode\x18\b \x01(\x0e2#.cerbero.contracts.v1.ExecutionModeR\rexecutionMode\x12-\n" +
	"\x12configuration_hash\x18\t \x01(\tR\x11configurationHash\"\xe8\t\n" +
	"\aFinding\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12D\n" +
	"\ffinding_type\x18\x03 \x01(\x0e2!.cerbero.contracts.v1.FindingTypeR\vfindingType\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.cerbero.contracts.v1.FindingStatusR\x06status\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12#\n" +
	"\n" +
	"confidence\x18\x06 \x01(\tH\x00R\n" +
	"confidence\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x129\n" +
	"\n" +
	"first_seen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\x0fprimary_rule_id\x18\r \x01(\tH\x01R\rprimaryRuleId\x88\x01\x01\x125\n" +
	"\x14primary_rule_version\x18\x0e \x01(\tH\x02R\x12primaryRuleVersion\x88\x01\x01\x123\n" +
	"\x13correlation_rule_id\x18\x0f \x01(\tH\x03R\x11correlationRuleId\x88\x01\x01\x12=\n" +
	"\x18correlation_rule_version\x18\x10 \x01(\tH\x04R\x16correlationRuleVersion\x88\x01\x01\x12J\n" +
	"\vdisposition\x18\x11 \x01(\x0e2(.cerbero.contracts.v1.FindingDispositionR\vdisposition\x123\n" +
	"\bmetadata\x18\x12 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12J\n" +
	"\x0eexecution_mode\x18\x13 \x01(\x0e2#.cerbero.contracts.v1.ExecutionModeR\rexecutionMode\x12:\n" +
	"\x06inputs\x18\x14 \x03(\v2\".cerbero.contracts.v1.FindingInputR\x06inputs\x12i\n" +
	"\x16correlation_provenance\x18\x15 \x01(\v22.cerbero.contracts.v1.FindingCorrelationProvenanceR\x15correlationProvenanceB\r\n" +
	"\v_confidenceB\x12\n" +
	"\x10_primary_rule_idB\x17\n" +
	"\x15_primary_rule_versionB\x16\n" +
	"\x14_correlation_rule_idB\x1b\n" +
	"\x19_correlation_rule_version*\x9e\x01\n" +
	"\vFindingType\x12\x1c\n" +
	"\x18FINDING_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FINDING_TYPE_DETECTION\x10\x01\x12\x1a\n" +
	"\x16FINDING_TYPE_THRESHOLD\x10\x02\x12\x1c\n" +
	"\x18FINDING_TYPE_CORRELATION\x10\x03\x12\x1b\n" +
	"\x17FINDING_TYPE_ANALYTICAL\x10\x04*\xc5\x01\n" +
	"\rFindingStatus\x12\x1e\n" +
	"\x1aFINDING_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FINDING_STATUS_OPEN\x10\x01\x12\x1f\n" +
	"\x1bFINDING_STATUS_ACKNOWLEDGED\x10\x02\x12\x1d\n" +
	"\x19FINDING_STATUS_SUPPRESSED\x10\x03\x12\x1b\n" +
	"\x17FINDING_STATUS_RESOLVED\x10\x04\x12\x1e\n" +
	"\x1aFINDING_STATUS_INVALIDATED\x10\x05*\xa6\x02\n" +
	"\x12FindingDisposition\x12#\n" +
	"\x1fFINDING_DISPOSITION_UNSPECIFIED\x10\x00\x12$\n" +
	" FINDING_DISPOSITION_UNDETERMINED\x10\x01\x12%\n" +
	"!FINDING_DISPOSITION_TRUE_POSITIVE\x10\x02\x12,\n" +
	"(FINDING_DISPOSITION_BENIGN_TRUE_POSITIVE\x10\x03\x12&\n" +
	"\"FINDING_DISPOSITION_FALSE_POSITIVE\x10\x04\x12!\n" +
	"\x1dFINDING_DISPOSITION_DUPLICATE\x10\x05\x12%\n" +
	"!FINDING_DISPOSITION_TEST_ACTIVITY\x10\x06B4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_finding_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_finding_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_finding_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_finding_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_finding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_finding_proto_rawDesc), len(file_cerbero_contracts_v1_finding_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_finding_proto_rawDescData
}

var file_cerbero_contracts_v1_finding_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cerbero_contracts_v1_finding_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cerbero_contracts_v1_finding_proto_goTypes = []any{
	(FindingType)(0),                     // 0: cerbero.contracts.v1.FindingType
	(FindingStatus)(0),                   // 1: cerbero.contracts.v1.FindingStatus
	(FindingDisposition)(0),              // 2: cerbero.contracts.v1.FindingDisposition
	(*FindingInput)(nil),                 // 3: cerbero.contracts.v1.FindingInput
	(*FindingCorrelationProvenance)(nil), // 4: cerbero.contracts.v1.FindingCorrelationProvenance
	(*Finding)(nil),                      // 5: cerbero.contracts.v1.Finding
	(*timestamppb.Timestamp)(nil),        // 6: google.protobuf.Timestamp
	(DetectionExecutionBackend)(0),       // 7: cerbero.contracts.v1.DetectionExecutionBackend
	(ExecutionMode)(0),                   // 8: cerbero.contracts.v1.ExecutionMode
	(*structpb.Struct)(nil),              // 9: google.protobuf.Struct
}
var file_cerbero_contracts_v1_finding_proto_depIdxs = []int32{
	6,  // 0: cerbero.contracts.v1.FindingCorrelationProvenance.window_start:type_name -> google.protobuf.Timestamp
	6,  // 1: cerbero.contracts.v1.FindingCorrelationProvenance.window_end:type_name -> google.protobuf.Timestamp
	7,  // 2: cerbero.contracts.v1.FindingCorrelationProvenance.execution_backend:type_name -> cerbero.contracts.v1.DetectionExecutionBackend
	8,  // 3: cerbero.contracts.v1.FindingCorrelationProvenance.execution_mode:type_name -> cerbero.contracts.v1.ExecutionMode
	0,  // 4: cerbero.contracts.v1.Finding.finding_type:type_name -> cerbero.contracts.v1.FindingType
	1,  // 5: cerbero.contracts.v1.Finding.status:type_name -> cerbero.contracts.v1.FindingStatus
	6,  // 6: cerbero.contracts.v1.Finding.first_seen:type_name -> google.protobuf.Timestamp
	6,  // 7: cerbero.contracts.v1.Finding.last_seen:type_name -> google.protobuf.Timestamp
	6,  // 8: cerbero.contracts.v1.Finding.created_at:type_name -> google.protobuf.Timestamp
	6,  // 9: cerbero.contracts.v1.Finding.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 10: cerbero.contracts.v1.Finding.disposition:type_name -> cerbero.contracts.v1.FindingDisposition
	9,  // 11: cerbero.contracts.v1.Finding.metadata:type_name -> google.protobuf.Struct
	8,  // 12: cerbero.contracts.v1.Finding.execution_mode:type_name -> cerbero.contracts.v1.ExecutionMode
	3,  // 13: cerbero.contracts.v1.Finding.inputs:type_name -> cerbero.contracts.v1.FindingInput
	4,  // 14: cerbero.contracts.v1.Finding.correlation_provenance:type_name -> cerbero.contracts.v1.FindingCorrelationProvenance
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_finding_proto_init() }
func file_cerbero_contracts_v1_finding_proto_init() {
	if File_cerbero_contracts_v1_finding_proto != nil {
		return
	}
	file_cerbero_contracts_v1_common_proto_init()
	file_cerbero_contracts_v1_signal_proto_init()
	file_cerbero_contracts_v1_finding_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_finding_proto_rawDesc), len(file_cerbero_contracts_v1_finding_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_finding_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_finding_proto_depIdxs,
		EnumInfos:         file_cerbero_contracts_v1_finding_proto_enumTypes,
		MessageInfos:      file_cerbero_contracts_v1_finding_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_finding_proto = out.File
	file_cerbero_contracts_v1_finding_proto_goTypes = nil
	file_cerbero_contracts_v1_finding_proto_depIdxs = nil
}
