// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/incident.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IncidentStatus is the governed operational Incident state machine.
type IncidentStatus int32

const (
	IncidentStatus_INCIDENT_STATUS_UNSPECIFIED   IncidentStatus = 0
	IncidentStatus_INCIDENT_STATUS_OPEN          IncidentStatus = 1
	IncidentStatus_INCIDENT_STATUS_TRIAGED       IncidentStatus = 2
	IncidentStatus_INCIDENT_STATUS_INVESTIGATING IncidentStatus = 3
	IncidentStatus_INCIDENT_STATUS_CONTAINED     IncidentStatus = 4
	IncidentStatus_INCIDENT_STATUS_RESOLVED      IncidentStatus = 5
	IncidentStatus_INCIDENT_STATUS_CLOSED        IncidentStatus = 6
	IncidentStatus_INCIDENT_STATUS_INVALIDATED   IncidentStatus = 7
)

// Enum value maps for IncidentStatus.
var (
	IncidentStatus_name = map[int32]string{
		0: "INCIDENT_STATUS_UNSPECIFIED",
		1: "INCIDENT_STATUS_OPEN",
		2: "INCIDENT_STATUS_TRIAGED",
		3: "INCIDENT_STATUS_INVESTIGATING",
		4: "INCIDENT_STATUS_CONTAINED",
		5: "INCIDENT_STATUS_RESOLVED",
		6: "INCIDENT_STATUS_CLOSED",
		7: "INCIDENT_STATUS_INVALIDATED",
	}
	IncidentStatus_value = map[string]int32{
		"INCIDENT_STATUS_UNSPECIFIED":   0,
		"INCIDENT_STATUS_OPEN":          1,
		"INCIDENT_STATUS_TRIAGED":       2,
		"INCIDENT_STATUS_INVESTIGATING": 3,
		"INCIDENT_STATUS_CONTAINED":     4,
		"INCIDENT_STATUS_RESOLVED":      5,
		"INCIDENT_STATUS_CLOSED":        6,
		"INCIDENT_STATUS_INVALIDATED":   7,
	}
)

func (x IncidentStatus) Enum() *IncidentStatus {
	p := new(IncidentStatus)
	*p = x
	return p
}

func (x IncidentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_incident_proto_enumTypes[0].Descriptor()
}

func (IncidentStatus) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_incident_proto_enumTypes[0]
}

func (x IncidentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentStatus.Descriptor instead.
func (IncidentStatus) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_incident_proto_rawDescGZIP(), []int{0}
}

// Incident groups related Findings while preserving the distinction from a Case.
type Incident struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IncidentId             string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	TenantId               string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status                 IncidentStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=cerbero.contracts.v1.IncidentStatus" json:"status,omitempty"`
	Severity               string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence             *string                `protobuf:"bytes,5,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Title                  string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description            string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	FirstSeen              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen               *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CorrelationReason      *string                `protobuf:"bytes,12,opt,name=correlation_reason,json=correlationReason,proto3,oneof" json:"correlation_reason,omitempty"`
	CorrelationRuleId      *string                `protobuf:"bytes,13,opt,name=correlation_rule_id,json=correlationRuleId,proto3,oneof" json:"correlation_rule_id,omitempty"`
	CorrelationRuleVersion *string                `protobuf:"bytes,14,opt,name=correlation_rule_version,json=correlationRuleVersion,proto3,oneof" json:"correlation_rule_version,omitempty"`
	WindowStart            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd              *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	OwnerUserId            *string                `protobuf:"bytes,17,opt,name=owner_user_id,json=ownerUserId,proto3,oneof" json:"owner_user_id,omitempty"`
	Disposition            *string                `protobuf:"bytes,18,opt,name=disposition,proto3,oneof" json:"disposition,omitempty"`
	Version                uint64                 `protobuf:"varint,19,opt,name=version,proto3" json:"version,omitempty"`
	FindingIds             []string               `protobuf:"bytes,20,rep,name=finding_ids,json=findingIds,proto3" json:"finding_ids,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_cerbero_contracts_v1_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_incident_proto_rawDescGZIP(), []int{0}
}

func (x *Incident) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *Incident) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Incident) GetStatus() IncidentStatus {
	if x != nil {
		return x.Status
	}
	return IncidentStatus_INCIDENT_STATUS_UNSPECIFIED
}

func (x *Incident) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Incident) GetConfidence() string {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return ""
}

func (x *Incident) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Incident) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Incident) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Incident) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Incident) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Incident) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Incident) GetCorrelationReason() string {
	if x != nil && x.CorrelationReason != nil {
		return *x.CorrelationReason
	}
	return ""
}

func (x *Incident) GetCorrelationRuleId() string {
	if x != nil && x.CorrelationRuleId != nil {
		return *x.CorrelationRuleId
	}
	return ""
}

func (x *Incident) GetCorrelationRuleVersion() string {
	if x != nil && x.CorrelationRuleVersion != nil {
		return *x.CorrelationRuleVersion
	}
	return ""
}

func (x *Incident) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *Incident) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *Incident) GetOwnerUserId() string {
	if x != nil && x.OwnerUserId != nil {
		return *x.OwnerUserId
	}
	return ""
}

func (x *Incident) GetDisposition() string {
	if x != nil && x.Disposition != nil {
		return *x.Disposition
	}
	return ""
}

func (x *Incident) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Incident) GetFindingIds() []string {
	if x != nil {
		return x.FindingIds
	}
	return nil
}

var File_cerbero_contracts_v1_incident_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_incident_proto_rawDesc = "" +
	"\n" +
	"#cerbero/contracts/v1/incident.proto\x12\x14cerbero.contracts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\b\n" +
	"\bIncident\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12<\n" +
	"\x06status\x18\x03 \x01(\x0e2$.cerbero.contracts.v1.IncidentStatusR\x06status\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12#\n" +
	"\n" +
	"confidence\x18\x05 \x01(\tH\x00R\n" +
	"confidence\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x129\n" +
	"\n" +
	"first_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\x12correlation_reason\x18\f \x01(\tH\x01R\x11correlationReason\x88\x01\x01\x123\n" +
	"\x13correlation_rule_id\x18\r \x01(\tH\x02R\x11correlationRuleId\x88\x01\x01\x12=\n" +
	"\x18correlation_rule_version\x18\x0e \x01(\tH\x03R\x16correlationRuleVersion\x88\x01\x01\x12=\n" +
	"\fwindow_start\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\x12'\n" +
	"\rowner_user_id\x18\x11 \x01(\tH\x04R\vownerUserId\x88\x01\x01\x12%\n" +
	"\vdisposition\x18\x12 \x01(\tH\x05R\vdisposition\x88\x01\x01\x12\x18\n" +
	"\aversion\x18\x13 \x01(\x04R\aversion\x12\x1f\n" +
	"\vfinding_ids\x18\x14 \x03(\tR\n" +
	"findingIdsB\r\n" +
	"\v_confidenceB\x15\n" +
	"\x13_correlation_reasonB\x16\n" +
	"\x14_correlation_rule_idB\x1b\n" +
	"\x19_correlation_rule_versionB\x10\n" +
	"\x0e_owner_user_idB\x0e\n" +
	"\f_disposition*\x85\x02\n" +
	"\x0eIncidentStatus\x12\x1f\n" +
	"\x1bINCIDENT_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INCIDENT_STATUS_OPEN\x10\x01\x12\x1b\n" +
	"\x17INCIDENT_STATUS_TRIAGED\x10\x02\x12!\n" +
	"\x1dINCIDENT_STATUS_INVESTIGATING\x10\x03\x12\x1d\n" +
	"\x19INCIDENT_STATUS_CONTAINED\x10\x04\x12\x1c\n" +
	"\x18INCIDENT_STATUS_RESOLVED\x10\x05\x12\x1a\n" +
	"\x16INCIDENT_STATUS_CLOSED\x10\x06\x12\x1f\n" +
	"\x1bINCIDENT_STATUS_INVALIDATED\x10\aB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_incident_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_incident_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_incident_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_incident_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_incident_proto_rawDesc), len(file_cerbero_contracts_v1_incident_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_incident_proto_rawDescData
}

var file_cerbero_contracts_v1_incident_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cerbero_contracts_v1_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbero_contracts_v1_incident_proto_goTypes = []any{
	(IncidentStatus)(0),           // 0: cerbero.contracts.v1.IncidentStatus
	(*Incident)(nil),              // 1: cerbero.contracts.v1.Incident
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_cerbero_contracts_v1_incident_proto_depIdxs = []int32{
	0, // 0: cerbero.contracts.v1.Incident.status:type_name -> cerbero.contracts.v1.IncidentStatus
	2, // 1: cerbero.contracts.v1.Incident.first_seen:type_name -> google.protobuf.Timestamp
	2, // 2: cerbero.contracts.v1.Incident.last_seen:type_name -> google.protobuf.Timestamp
	2, // 3: cerbero.contracts.v1.Incident.created_at:type_name -> google.protobuf.Timestamp
	2, // 4: cerbero.contracts.v1.Incident.updated_at:type_name -> google.protobuf.Timestamp
	2, // 5: cerbero.contracts.v1.Incident.window_start:type_name -> google.protobuf.Timestamp
	2, // 6: cerbero.contracts.v1.Incident.window_end:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_incident_proto_init() }
func file_cerbero_contracts_v1_incident_proto_init() {
	if File_cerbero_contracts_v1_incident_proto != nil {
		return
	}
	file_cerbero_contracts_v1_incident_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_incident_proto_rawDesc), len(file_cerbero_contracts_v1_incident_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_incident_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_incident_proto_depIdxs,
		EnumInfos:         file_cerbero_contracts_v1_incident_proto_enumTypes,
		MessageInfos:      file_cerbero_contracts_v1_incident_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_incident_proto = out.File
	file_cerbero_contracts_v1_incident_proto_goTypes = nil
	file_cerbero_contracts_v1_incident_proto_depIdxs = nil
}
