// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/normalized_event.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NormalizedEvent is an OCSF derivation of an immutable RawEvent.
type NormalizedEvent struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	NormalizedEventId       string                 `protobuf:"bytes,1,opt,name=normalized_event_id,json=normalizedEventId,proto3" json:"normalized_event_id,omitempty"`
	RawEventId              string                 `protobuf:"bytes,2,opt,name=raw_event_id,json=rawEventId,proto3" json:"raw_event_id,omitempty"`
	TenantId                string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NormalizedAt            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=normalized_at,json=normalizedAt,proto3" json:"normalized_at,omitempty"`
	OcsfVersion             string                 `protobuf:"bytes,5,opt,name=ocsf_version,json=ocsfVersion,proto3" json:"ocsf_version,omitempty"`
	ClassUid                uint32                 `protobuf:"varint,6,opt,name=class_uid,json=classUid,proto3" json:"class_uid,omitempty"`
	CategoryUid             uint32                 `protobuf:"varint,7,opt,name=category_uid,json=categoryUid,proto3" json:"category_uid,omitempty"`
	Severity                *uint32                `protobuf:"varint,8,opt,name=severity,proto3,oneof" json:"severity,omitempty"`
	ActivityId              *uint32                `protobuf:"varint,9,opt,name=activity_id,json=activityId,proto3,oneof" json:"activity_id,omitempty"`
	OcsfEvent               *structpb.Struct       `protobuf:"bytes,10,opt,name=ocsf_event,json=ocsfEvent,proto3" json:"ocsf_event,omitempty"`
	ParserId                string                 `protobuf:"bytes,11,opt,name=parser_id,json=parserId,proto3" json:"parser_id,omitempty"`
	ParserVersion           string                 `protobuf:"bytes,12,opt,name=parser_version,json=parserVersion,proto3" json:"parser_version,omitempty"`
	NormalizationStatus     NormalizationStatus    `protobuf:"varint,13,opt,name=normalization_status,json=normalizationStatus,proto3,enum=cerbero.contracts.v1.NormalizationStatus" json:"normalization_status,omitempty"`
	NormalizedHashAlgorithm string                 `protobuf:"bytes,14,opt,name=normalized_hash_algorithm,json=normalizedHashAlgorithm,proto3" json:"normalized_hash_algorithm,omitempty"`
	NormalizedHash          string                 `protobuf:"bytes,15,opt,name=normalized_hash,json=normalizedHash,proto3" json:"normalized_hash,omitempty"`
	PipelineVersion         string                 `protobuf:"bytes,16,opt,name=pipeline_version,json=pipelineVersion,proto3" json:"pipeline_version,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NormalizedEvent) Reset() {
	*x = NormalizedEvent{}
	mi := &file_cerbero_contracts_v1_normalized_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedEvent) ProtoMessage() {}

func (x *NormalizedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_normalized_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedEvent.ProtoReflect.Descriptor instead.
func (*NormalizedEvent) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_normalized_event_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizedEvent) GetNormalizedEventId() string {
	if x != nil {
		return x.NormalizedEventId
	}
	return ""
}

func (x *NormalizedEvent) GetRawEventId() string {
	if x != nil {
		return x.RawEventId
	}
	return ""
}

func (x *NormalizedEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *NormalizedEvent) GetNormalizedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NormalizedAt
	}
	return nil
}

func (x *NormalizedEvent) GetOcsfVersion() string {
	if x != nil {
		return x.OcsfVersion
	}
	return ""
}

func (x *NormalizedEvent) GetClassUid() uint32 {
	if x != nil {
		return x.ClassUid
	}
	return 0
}

func (x *NormalizedEvent) GetCategoryUid() uint32 {
	if x != nil {
		return x.CategoryUid
	}
	return 0
}

func (x *NormalizedEvent) GetSeverity() uint32 {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return 0
}

func (x *NormalizedEvent) GetActivityId() uint32 {
	if x != nil && x.ActivityId != nil {
		return *x.ActivityId
	}
	return 0
}

func (x *NormalizedEvent) GetOcsfEvent() *structpb.Struct {
	if x != nil {
		return x.OcsfEvent
	}
	return nil
}

func (x *NormalizedEvent) GetParserId() string {
	if x != nil {
		return x.ParserId
	}
	return ""
}

func (x *NormalizedEvent) GetParserVersion() string {
	if x != nil {
		return x.ParserVersion
	}
	return ""
}

func (x *NormalizedEvent) GetNormalizationStatus() NormalizationStatus {
	if x != nil {
		return x.NormalizationStatus
	}
	return NormalizationStatus_NORMALIZATION_STATUS_UNSPECIFIED
}

func (x *NormalizedEvent) GetNormalizedHashAlgorithm() string {
	if x != nil {
		return x.NormalizedHashAlgorithm
	}
	return ""
}

func (x *NormalizedEvent) GetNormalizedHash() string {
	if x != nil {
		return x.NormalizedHash
	}
	return ""
}

func (x *NormalizedEvent) GetPipelineVersion() string {
	if x != nil {
		return x.PipelineVersion
	}
	return ""
}

var File_cerbero_contracts_v1_normalized_event_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_normalized_event_proto_rawDesc = "" +
	"\n" +
	"+cerbero/contracts/v1/normalized_event.proto\x12\x14cerbero.contracts.v1\x1a!cerbero/contracts/v1/common.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x05\n" +
	"\x0fNormalizedEvent\x12.\n" +
	"\x13normalized_event_id\x18\x01 \x01(\tR\x11normalizedEventId\x12 \n" +
	"\fraw_event_id\x18\x02 \x01(\tR\n" +
	"rawEventId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12?\n" +
	"\rnormalized_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fnormalizedAt\x12!\n" +
	"\focsf_version\x18\x05 \x01(\tR\vocsfVersion\x12\x1b\n" +
	"\tclass_uid\x18\x06 \x01(\rR\bclassUid\x12!\n" +
	"\fcategory_uid\x18\a \x01(\rR\vcategoryUid\x12\x1f\n" +
	"\bseverity\x18\b \x01(\rH\x00R\bseverity\x88\x01\x01\x12$\n" +
	"\vactivity_id\x18\t \x01(\rH\x01R\n" +
	"activityId\x88\x01\x01\x126\n" +
	"\n" +
	"ocsf_event\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\tocsfEvent\x12\x1b\n" +
	"\tparser_id\x18\v \x01(\tR\bparserId\x12%\n" +
	"\x0eparser_version\x18\f \x01(\tR\rparserVersion\x12\\\n" +
	"\x14normalization_status\x18\r \x01(\x0e2).cerbero.contracts.v1.NormalizationStatusR\x13normalizationStatus\x12:\n" +
	"\x19normalized_hash_algorithm\x18\x0e \x01(\tR\x17normalizedHashAlgorithm\x12'\n" +
	"\x0fnormalized_hash\x18\x0f \x01(\tR\x0enormalizedHash\x12)\n" +
	"\x10pipeline_version\x18\x10 \x01(\tR\x0fpipelineVersionB\v\n" +
	"\t_severityB\x0e\n" +
	"\f_activity_idB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_normalized_event_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_normalized_event_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_normalized_event_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_normalized_event_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_normalized_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_normalized_event_proto_rawDesc), len(file_cerbero_contracts_v1_normalized_event_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_normalized_event_proto_rawDescData
}

var file_cerbero_contracts_v1_normalized_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbero_contracts_v1_normalized_event_proto_goTypes = []any{
	(*NormalizedEvent)(nil),       // 0: cerbero.contracts.v1.NormalizedEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
	(NormalizationStatus)(0),      // 3: cerbero.contracts.v1.NormalizationStatus
}
var file_cerbero_contracts_v1_normalized_event_proto_depIdxs = []int32{
	1, // 0: cerbero.contracts.v1.NormalizedEvent.normalized_at:type_name -> google.protobuf.Timestamp
	2, // 1: cerbero.contracts.v1.NormalizedEvent.ocsf_event:type_name -> google.protobuf.Struct
	3, // 2: cerbero.contracts.v1.NormalizedEvent.normalization_status:type_name -> cerbero.contracts.v1.NormalizationStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_normalized_event_proto_init() }
func file_cerbero_contracts_v1_normalized_event_proto_init() {
	if File_cerbero_contracts_v1_normalized_event_proto != nil {
		return
	}
	file_cerbero_contracts_v1_common_proto_init()
	file_cerbero_contracts_v1_normalized_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_normalized_event_proto_rawDesc), len(file_cerbero_contracts_v1_normalized_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_normalized_event_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_normalized_event_proto_depIdxs,
		MessageInfos:      file_cerbero_contracts_v1_normalized_event_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_normalized_event_proto = out.File
	file_cerbero_contracts_v1_normalized_event_proto_goTypes = nil
	file_cerbero_contracts_v1_normalized_event_proto_depIdxs = nil
}
