// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/raw_event.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RawEvent preserves the exact bytes accepted at the ingest boundary and their acquisition metadata.
type RawEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SourceId         string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SensorId         string                 `protobuf:"bytes,4,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	EventTime        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	IngestTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ingest_time,json=ingestTime,proto3" json:"ingest_time,omitempty"`
	ContentType      string                 `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Encoding         string                 `protobuf:"bytes,8,opt,name=encoding,proto3" json:"encoding,omitempty"`
	RawPayload       []byte                 `protobuf:"bytes,9,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	RawSize          uint64                 `protobuf:"varint,10,opt,name=raw_size,json=rawSize,proto3" json:"raw_size,omitempty"`
	RawHashAlgorithm string                 `protobuf:"bytes,11,opt,name=raw_hash_algorithm,json=rawHashAlgorithm,proto3" json:"raw_hash_algorithm,omitempty"`
	RawHash          string                 `protobuf:"bytes,12,opt,name=raw_hash,json=rawHash,proto3" json:"raw_hash,omitempty"`
	Transport        string                 `protobuf:"bytes,13,opt,name=transport,proto3" json:"transport,omitempty"`
	RemoteIdentity   string                 `protobuf:"bytes,14,opt,name=remote_identity,json=remoteIdentity,proto3" json:"remote_identity,omitempty"`
	SequenceNumber   *uint64                `protobuf:"varint,15,opt,name=sequence_number,json=sequenceNumber,proto3,oneof" json:"sequence_number,omitempty"`
	IntegrityStatus  IntegrityStatus        `protobuf:"varint,16,opt,name=integrity_status,json=integrityStatus,proto3,enum=cerbero.contracts.v1.IntegrityStatus" json:"integrity_status,omitempty"`
	PipelineVersion  string                 `protobuf:"bytes,17,opt,name=pipeline_version,json=pipelineVersion,proto3" json:"pipeline_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RawEvent) Reset() {
	*x = RawEvent{}
	mi := &file_cerbero_contracts_v1_raw_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawEvent) ProtoMessage() {}

func (x *RawEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_raw_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawEvent.ProtoReflect.Descriptor instead.
func (*RawEvent) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_raw_event_proto_rawDescGZIP(), []int{0}
}

func (x *RawEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RawEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RawEvent) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *RawEvent) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *RawEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *RawEvent) GetIngestTime() *timestamppb.Timestamp {
	if x != nil {
		return x.IngestTime
	}
	return nil
}

func (x *RawEvent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RawEvent) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

func (x *RawEvent) GetRawPayload() []byte {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *RawEvent) GetRawSize() uint64 {
	if x != nil {
		return x.RawSize
	}
	return 0
}

func (x *RawEvent) GetRawHashAlgorithm() string {
	if x != nil {
		return x.RawHashAlgorithm
	}
	return ""
}

func (x *RawEvent) GetRawHash() string {
	if x != nil {
		return x.RawHash
	}
	return ""
}

func (x *RawEvent) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *RawEvent) GetRemoteIdentity() string {
	if x != nil {
		return x.RemoteIdentity
	}
	return ""
}

func (x *RawEvent) GetSequenceNumber() uint64 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *RawEvent) GetIntegrityStatus() IntegrityStatus {
	if x != nil {
		return x.IntegrityStatus
	}
	return IntegrityStatus_INTEGRITY_STATUS_UNSPECIFIED
}

func (x *RawEvent) GetPipelineVersion() string {
	if x != nil {
		return x.PipelineVersion
	}
	return ""
}

var File_cerbero_contracts_v1_raw_event_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_raw_event_proto_rawDesc = "" +
	"\n" +
	"$cerbero/contracts/v1/raw_event.proto\x12\x14cerbero.contracts.v1\x1a!cerbero/contracts/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbe\x05\n" +
	"\bRawEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1b\n" +
	"\tsensor_id\x18\x04 \x01(\tR\bsensorId\x129\n" +
	"\n" +
	"event_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12;\n" +
	"\vingest_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"ingestTime\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x12\x1a\n" +
	"\bencoding\x18\b \x01(\tR\bencoding\x12\x1f\n" +
	"\vraw_payload\x18\t \x01(\fR\n" +
	"rawPayload\x12\x19\n" +
	"\braw_size\x18\n" +
	" \x01(\x04R\arawSize\x12,\n" +
	"\x12raw_hash_algorithm\x18\v \x01(\tR\x10rawHashAlgorithm\x12\x19\n" +
	"\braw_hash\x18\f \x01(\tR\arawHash\x12\x1c\n" +
	"\ttransport\x18\r \x01(\tR\ttransport\x12'\n" +
	"\x0fremote_identity\x18\x0e \x01(\tR\x0eremoteIdentity\x12,\n" +
	"\x0fsequence_number\x18\x0f \x01(\x04H\x00R\x0esequenceNumber\x88\x01\x01\x12P\n" +
	"\x10integrity_status\x18\x10 \x01(\x0e2%.cerbero.contracts.v1.IntegrityStatusR\x0fintegrityStatus\x12)\n" +
	"\x10pipeline_version\x18\x11 \x01(\tR\x0fpipelineVersionB\x12\n" +
	"\x10_sequence_numberB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_raw_event_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_raw_event_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_raw_event_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_raw_event_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_raw_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_raw_event_proto_rawDesc), len(file_cerbero_contracts_v1_raw_event_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_raw_event_proto_rawDescData
}

var file_cerbero_contracts_v1_raw_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbero_contracts_v1_raw_event_proto_goTypes = []any{
	(*RawEvent)(nil),              // 0: cerbero.contracts.v1.RawEvent
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(IntegrityStatus)(0),          // 2: cerbero.contracts.v1.IntegrityStatus
}
var file_cerbero_contracts_v1_raw_event_proto_depIdxs = []int32{
	1, // 0: cerbero.contracts.v1.RawEvent.event_time:type_name -> google.protobuf.Timestamp
	1, // 1: cerbero.contracts.v1.RawEvent.ingest_time:type_name -> google.protobuf.Timestamp
	2, // 2: cerbero.contracts.v1.RawEvent.integrity_status:type_name -> cerbero.contracts.v1.IntegrityStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_raw_event_proto_init() }
func file_cerbero_contracts_v1_raw_event_proto_init() {
	if File_cerbero_contracts_v1_raw_event_proto != nil {
		return
	}
	file_cerbero_contracts_v1_common_proto_init()
	file_cerbero_contracts_v1_raw_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_raw_event_proto_rawDesc), len(file_cerbero_contracts_v1_raw_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_raw_event_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_raw_event_proto_depIdxs,
		MessageInfos:      file_cerbero_contracts_v1_raw_event_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_raw_event_proto = out.File
	file_cerbero_contracts_v1_raw_event_proto_goTypes = nil
	file_cerbero_contracts_v1_raw_event_proto_depIdxs = nil
}
