// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/signal.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SignalRuleType identifies the detection-rule family associated with a Signal.
type SignalRuleType int32

const (
	SignalRuleType_SIGNAL_RULE_TYPE_UNSPECIFIED SignalRuleType = 0
	SignalRuleType_SIGNAL_RULE_TYPE_EVENT       SignalRuleType = 1
	SignalRuleType_SIGNAL_RULE_TYPE_THRESHOLD   SignalRuleType = 2
	SignalRuleType_SIGNAL_RULE_TYPE_CORRELATION SignalRuleType = 3
)

// Enum value maps for SignalRuleType.
var (
	SignalRuleType_name = map[int32]string{
		0: "SIGNAL_RULE_TYPE_UNSPECIFIED",
		1: "SIGNAL_RULE_TYPE_EVENT",
		2: "SIGNAL_RULE_TYPE_THRESHOLD",
		3: "SIGNAL_RULE_TYPE_CORRELATION",
	}
	SignalRuleType_value = map[string]int32{
		"SIGNAL_RULE_TYPE_UNSPECIFIED": 0,
		"SIGNAL_RULE_TYPE_EVENT":       1,
		"SIGNAL_RULE_TYPE_THRESHOLD":   2,
		"SIGNAL_RULE_TYPE_CORRELATION": 3,
	}
)

func (x SignalRuleType) Enum() *SignalRuleType {
	p := new(SignalRuleType)
	*p = x
	return p
}

func (x SignalRuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalRuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_signal_proto_enumTypes[0].Descriptor()
}

func (SignalRuleType) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_signal_proto_enumTypes[0]
}

func (x SignalRuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalRuleType.Descriptor instead.
func (SignalRuleType) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_signal_proto_rawDescGZIP(), []int{0}
}

// SignalStatus records the analytical lifecycle state without deleting history.
type SignalStatus int32

const (
	SignalStatus_SIGNAL_STATUS_UNSPECIFIED SignalStatus = 0
	SignalStatus_SIGNAL_STATUS_ACTIVE      SignalStatus = 1
	SignalStatus_SIGNAL_STATUS_SUPPRESSED  SignalStatus = 2
	SignalStatus_SIGNAL_STATUS_PROMOTED    SignalStatus = 3
	SignalStatus_SIGNAL_STATUS_INVALIDATED SignalStatus = 4
)

// Enum value maps for SignalStatus.
var (
	SignalStatus_name = map[int32]string{
		0: "SIGNAL_STATUS_UNSPECIFIED",
		1: "SIGNAL_STATUS_ACTIVE",
		2: "SIGNAL_STATUS_SUPPRESSED",
		3: "SIGNAL_STATUS_PROMOTED",
		4: "SIGNAL_STATUS_INVALIDATED",
	}
	SignalStatus_value = map[string]int32{
		"SIGNAL_STATUS_UNSPECIFIED": 0,
		"SIGNAL_STATUS_ACTIVE":      1,
		"SIGNAL_STATUS_SUPPRESSED":  2,
		"SIGNAL_STATUS_PROMOTED":    3,
		"SIGNAL_STATUS_INVALIDATED": 4,
	}
)

func (x SignalStatus) Enum() *SignalStatus {
	p := new(SignalStatus)
	*p = x
	return p
}

func (x SignalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_signal_proto_enumTypes[1].Descriptor()
}

func (SignalStatus) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_signal_proto_enumTypes[1]
}

func (x SignalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalStatus.Descriptor instead.
func (SignalStatus) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_signal_proto_rawDescGZIP(), []int{1}
}

// SignalInputType identifies an object that contributed to the Signal match.
type SignalInputType int32

const (
	SignalInputType_SIGNAL_INPUT_TYPE_UNSPECIFIED      SignalInputType = 0
	SignalInputType_SIGNAL_INPUT_TYPE_NORMALIZED_EVENT SignalInputType = 1
	SignalInputType_SIGNAL_INPUT_TYPE_SIGNAL           SignalInputType = 2
	SignalInputType_SIGNAL_INPUT_TYPE_ENTITY           SignalInputType = 3
)

// Enum value maps for SignalInputType.
var (
	SignalInputType_name = map[int32]string{
		0: "SIGNAL_INPUT_TYPE_UNSPECIFIED",
		1: "SIGNAL_INPUT_TYPE_NORMALIZED_EVENT",
		2: "SIGNAL_INPUT_TYPE_SIGNAL",
		3: "SIGNAL_INPUT_TYPE_ENTITY",
	}
	SignalInputType_value = map[string]int32{
		"SIGNAL_INPUT_TYPE_UNSPECIFIED":      0,
		"SIGNAL_INPUT_TYPE_NORMALIZED_EVENT": 1,
		"SIGNAL_INPUT_TYPE_SIGNAL":           2,
		"SIGNAL_INPUT_TYPE_ENTITY":           3,
	}
)

func (x SignalInputType) Enum() *SignalInputType {
	p := new(SignalInputType)
	*p = x
	return p
}

func (x SignalInputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalInputType) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_signal_proto_enumTypes[2].Descriptor()
}

func (SignalInputType) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_signal_proto_enumTypes[2]
}

func (x SignalInputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalInputType.Descriptor instead.
func (SignalInputType) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_signal_proto_rawDescGZIP(), []int{2}
}

// DetectionExecutionBackend identifies the backend that evaluated the detection plan.
type DetectionExecutionBackend int32

const (
	DetectionExecutionBackend_DETECTION_EXECUTION_BACKEND_UNSPECIFIED DetectionExecutionBackend = 0
	DetectionExecutionBackend_DETECTION_EXECUTION_BACKEND_CLICKHOUSE  DetectionExecutionBackend = 1
	DetectionExecutionBackend_DETECTION_EXECUTION_BACKEND_STREAM      DetectionExecutionBackend = 2
)

// Enum value maps for DetectionExecutionBackend.
var (
	DetectionExecutionBackend_name = map[int32]string{
		0: "DETECTION_EXECUTION_BACKEND_UNSPECIFIED",
		1: "DETECTION_EXECUTION_BACKEND_CLICKHOUSE",
		2: "DETECTION_EXECUTION_BACKEND_STREAM",
	}
	DetectionExecutionBackend_value = map[string]int32{
		"DETECTION_EXECUTION_BACKEND_UNSPECIFIED": 0,
		"DETECTION_EXECUTION_BACKEND_CLICKHOUSE":  1,
		"DETECTION_EXECUTION_BACKEND_STREAM":      2,
	}
)

func (x DetectionExecutionBackend) Enum() *DetectionExecutionBackend {
	p := new(DetectionExecutionBackend)
	*p = x
	return p
}

func (x DetectionExecutionBackend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectionExecutionBackend) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbero_contracts_v1_signal_proto_enumTypes[3].Descriptor()
}

func (DetectionExecutionBackend) Type() protoreflect.EnumType {
	return &file_cerbero_contracts_v1_signal_proto_enumTypes[3]
}

func (x DetectionExecutionBackend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetectionExecutionBackend.Descriptor instead.
func (DetectionExecutionBackend) EnumDescriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_signal_proto_rawDescGZIP(), []int{3}
}

// SignalProvenance captures execution facts not already represented by Signal fields or inputs.
type SignalProvenance struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	EvaluatedAt      *timestamppb.Timestamp    `protobuf:"bytes,1,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	ExecutionBackend DetectionExecutionBackend `protobuf:"varint,2,opt,name=execution_backend,json=executionBackend,proto3,enum=cerbero.contracts.v1.DetectionExecutionBackend" json:"execution_backend,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignalProvenance) Reset() {
	*x = SignalProvenance{}
	mi := &file_cerbero_contracts_v1_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalProvenance) ProtoMessage() {}

func (x *SignalProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalProvenance.ProtoReflect.Descriptor instead.
func (*SignalProvenance) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalProvenance) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

func (x *SignalProvenance) GetExecutionBackend() DetectionExecutionBackend {
	if x != nil {
		return x.ExecutionBackend
	}
	return DetectionExecutionBackend_DETECTION_EXECUTION_BACKEND_UNSPECIFIED
}

// SignalInput preserves one ordered object that contributed to a Signal.
type SignalInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	InputType     SignalInputType        `protobuf:"varint,2,opt,name=input_type,json=inputType,proto3,enum=cerbero.contracts.v1.SignalInputType" json:"input_type,omitempty"`
	InputId       string                 `protobuf:"bytes,3,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	Relation      string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	Ordinal       uint32                 `protobuf:"varint,5,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalInput) Reset() {
	*x = SignalInput{}
	mi := &file_cerbero_contracts_v1_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalInput) ProtoMessage() {}

func (x *SignalInput) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalInput.ProtoReflect.Descriptor instead.
func (*SignalInput) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_signal_proto_rawDescGZIP(), []int{1}
}

func (x *SignalInput) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *SignalInput) GetInputType() SignalInputType {
	if x != nil {
		return x.InputType
	}
	return SignalInputType_SIGNAL_INPUT_TYPE_UNSPECIFIED
}

func (x *SignalInput) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *SignalInput) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *SignalInput) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

// Signal is the canonical v1 wire representation of an elementary detection match.
type Signal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SignalId        string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RuleId          string                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleVersion     string                 `protobuf:"bytes,4,opt,name=rule_version,json=ruleVersion,proto3" json:"rule_version,omitempty"`
	RuleType        SignalRuleType         `protobuf:"varint,5,opt,name=rule_type,json=ruleType,proto3,enum=cerbero.contracts.v1.SignalRuleType" json:"rule_type,omitempty"`
	Severity        string                 `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Confidence      *string                `protobuf:"bytes,7,opt,name=confidence,proto3,oneof" json:"confidence,omitempty"`
	Status          SignalStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=cerbero.contracts.v1.SignalStatus" json:"status,omitempty"`
	FirstObservedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=first_observed_at,json=firstObservedAt,proto3" json:"first_observed_at,omitempty"`
	LastObservedAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_observed_at,json=lastObservedAt,proto3" json:"last_observed_at,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExecutionMode   ExecutionMode          `protobuf:"varint,12,opt,name=execution_mode,json=executionMode,proto3,enum=cerbero.contracts.v1.ExecutionMode" json:"execution_mode,omitempty"`
	SourceCount     uint64                 `protobuf:"varint,13,opt,name=source_count,json=sourceCount,proto3" json:"source_count,omitempty"`
	EventCount      uint64                 `protobuf:"varint,14,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	Summary         string                 `protobuf:"bytes,15,opt,name=summary,proto3" json:"summary,omitempty"`
	Provenance      *SignalProvenance      `protobuf:"bytes,16,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Inputs          []*SignalInput         `protobuf:"bytes,17,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_cerbero_contracts_v1_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_signal_proto_rawDescGZIP(), []int{2}
}

func (x *Signal) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *Signal) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Signal) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Signal) GetRuleVersion() string {
	if x != nil {
		return x.RuleVersion
	}
	return ""
}

func (x *Signal) GetRuleType() SignalRuleType {
	if x != nil {
		return x.RuleType
	}
	return SignalRuleType_SIGNAL_RULE_TYPE_UNSPECIFIED
}

func (x *Signal) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Signal) GetConfidence() string {
	if x != nil && x.Confidence != nil {
		return *x.Confidence
	}
	return ""
}

func (x *Signal) GetStatus() SignalStatus {
	if x != nil {
		return x.Status
	}
	return SignalStatus_SIGNAL_STATUS_UNSPECIFIED
}

func (x *Signal) GetFirstObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstObservedAt
	}
	return nil
}

func (x *Signal) GetLastObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastObservedAt
	}
	return nil
}

func (x *Signal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Signal) GetExecutionMode() ExecutionMode {
	if x != nil {
		return x.ExecutionMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

func (x *Signal) GetSourceCount() uint64 {
	if x != nil {
		return x.SourceCount
	}
	return 0
}

func (x *Signal) GetEventCount() uint64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *Signal) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Signal) GetProvenance() *SignalProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *Signal) GetInputs() []*SignalInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

var File_cerbero_contracts_v1_signal_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_signal_proto_rawDesc = "" +
	"\n" +
	"!cerbero/contracts/v1/signal.proto\x12\x14cerbero.contracts.v1\x1a!cerbero/contracts/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x01\n" +
	"\x10SignalProvenance\x12=\n" +
	"\fevaluated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vevaluatedAt\x12\\\n" +
	"\x11execution_backend\x18\x02 \x01(\x0e2/.cerbero.contracts.v1.DetectionExecutionBackendR\x10executionBackend\"\xc1\x01\n" +
	"\vSignalInput\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12D\n" +
	"\n" +
	"input_type\x18\x02 \x01(\x0e2%.cerbero.contracts.v1.SignalInputTypeR\tinputType\x12\x19\n" +
	"\binput_id\x18\x03 \x01(\tR\ainputId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12\x18\n" +
	"\aordinal\x18\x05 \x01(\rR\aordinal\"\xc3\x06\n" +
	"\x06Signal\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12!\n" +
	"\frule_version\x18\x04 \x01(\tR\vruleVersion\x12A\n" +
	"\trule_type\x18\x05 \x01(\x0e2$.cerbero.contracts.v1.SignalRuleTypeR\bruleType\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\tR\bseverity\x12#\n" +
	"\n" +
	"confidence\x18\a \x01(\tH\x00R\n" +
	"confidence\x88\x01\x01\x12:\n" +
	"\x06status\x18\b \x01(\x0e2\".cerbero.contracts.v1.SignalStatusR\x06status\x12F\n" +
	"\x11first_observed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0ffirstObservedAt\x12D\n" +
	"\x10last_observed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0elastObservedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12J\n" +
	"\x0eexecution_mode\x18\f \x01(\x0e2#.cerbero.contracts.v1.ExecutionModeR\rexecutionMode\x12!\n" +
	"\fsource_count\x18\r \x01(\x04R\vsourceCount\x12\x1f\n" +
	"\vevent_count\x18\x0e \x01(\x04R\n" +
	"eventCount\x12\x18\n" +
	"\asummary\x18\x0f \x01(\tR\asummary\x12F\n" +
	"\n" +
	"provenance\x18\x10 \x01(\v2&.cerbero.contracts.v1.SignalProvenanceR\n" +
	"provenance\x129\n" +
	"\x06inputs\x18\x11 \x03(\v2!.cerbero.contracts.v1.SignalInputR\x06inputsB\r\n" +
	"\v_confidence*\x90\x01\n" +
	"\x0eSignalRuleType\x12 \n" +
	"\x1cSIGNAL_RULE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SIGNAL_RULE_TYPE_EVENT\x10\x01\x12\x1e\n" +
	"\x1aSIGNAL_RULE_TYPE_THRESHOLD\x10\x02\x12 \n" +
	"\x1cSIGNAL_RULE_TYPE_CORRELATION\x10\x03*\xa0\x01\n" +
	"\fSignalStatus\x12\x1d\n" +
	"\x19SIGNAL_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SIGNAL_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18SIGNAL_STATUS_SUPPRESSED\x10\x02\x12\x1a\n" +
	"\x16SIGNAL_STATUS_PROMOTED\x10\x03\x12\x1d\n" +
	"\x19SIGNAL_STATUS_INVALIDATED\x10\x04*\x98\x01\n" +
	"\x0fSignalInputType\x12!\n" +
	"\x1dSIGNAL_INPUT_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"SIGNAL_INPUT_TYPE_NORMALIZED_EVENT\x10\x01\x12\x1c\n" +
	"\x18SIGNAL_INPUT_TYPE_SIGNAL\x10\x02\x12\x1c\n" +
	"\x18SIGNAL_INPUT_TYPE_ENTITY\x10\x03*\x9c\x01\n" +
	"\x19DetectionExecutionBackend\x12+\n" +
	"'DETECTION_EXECUTION_BACKEND_UNSPECIFIED\x10\x00\x12*\n" +
	"&DETECTION_EXECUTION_BACKEND_CLICKHOUSE\x10\x01\x12&\n" +
	"\"DETECTION_EXECUTION_BACKEND_STREAM\x10\x02B4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_signal_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_signal_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_signal_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_signal_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_signal_proto_rawDesc), len(file_cerbero_contracts_v1_signal_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_signal_proto_rawDescData
}

var file_cerbero_contracts_v1_signal_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_cerbero_contracts_v1_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cerbero_contracts_v1_signal_proto_goTypes = []any{
	(SignalRuleType)(0),            // 0: cerbero.contracts.v1.SignalRuleType
	(SignalStatus)(0),              // 1: cerbero.contracts.v1.SignalStatus
	(SignalInputType)(0),           // 2: cerbero.contracts.v1.SignalInputType
	(DetectionExecutionBackend)(0), // 3: cerbero.contracts.v1.DetectionExecutionBackend
	(*SignalProvenance)(nil),       // 4: cerbero.contracts.v1.SignalProvenance
	(*SignalInput)(nil),            // 5: cerbero.contracts.v1.SignalInput
	(*Signal)(nil),                 // 6: cerbero.contracts.v1.Signal
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
	(ExecutionMode)(0),             // 8: cerbero.contracts.v1.ExecutionMode
}
var file_cerbero_contracts_v1_signal_proto_depIdxs = []int32{
	7,  // 0: cerbero.contracts.v1.SignalProvenance.evaluated_at:type_name -> google.protobuf.Timestamp
	3,  // 1: cerbero.contracts.v1.SignalProvenance.execution_backend:type_name -> cerbero.contracts.v1.DetectionExecutionBackend
	2,  // 2: cerbero.contracts.v1.SignalInput.input_type:type_name -> cerbero.contracts.v1.SignalInputType
	0,  // 3: cerbero.contracts.v1.Signal.rule_type:type_name -> cerbero.contracts.v1.SignalRuleType
	1,  // 4: cerbero.contracts.v1.Signal.status:type_name -> cerbero.contracts.v1.SignalStatus
	7,  // 5: cerbero.contracts.v1.Signal.first_observed_at:type_name -> google.protobuf.Timestamp
	7,  // 6: cerbero.contracts.v1.Signal.last_observed_at:type_name -> google.protobuf.Timestamp
	7,  // 7: cerbero.contracts.v1.Signal.created_at:type_name -> google.protobuf.Timestamp
	8,  // 8: cerbero.contracts.v1.Signal.execution_mode:type_name -> cerbero.contracts.v1.ExecutionMode
	4,  // 9: cerbero.contracts.v1.Signal.provenance:type_name -> cerbero.contracts.v1.SignalProvenance
	5,  // 10: cerbero.contracts.v1.Signal.inputs:type_name -> cerbero.contracts.v1.SignalInput
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_signal_proto_init() }
func file_cerbero_contracts_v1_signal_proto_init() {
	if File_cerbero_contracts_v1_signal_proto != nil {
		return
	}
	file_cerbero_contracts_v1_common_proto_init()
	file_cerbero_contracts_v1_signal_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_signal_proto_rawDesc), len(file_cerbero_contracts_v1_signal_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_signal_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_signal_proto_depIdxs,
		EnumInfos:         file_cerbero_contracts_v1_signal_proto_enumTypes,
		MessageInfos:      file_cerbero_contracts_v1_signal_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_signal_proto = out.File
	file_cerbero_contracts_v1_signal_proto_goTypes = nil
	file_cerbero_contracts_v1_signal_proto_depIdxs = nil
}
