// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbero/contracts/v1/transformation.proto

package contractsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transformation records provenance for a material processing step.
type Transformation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransformationId  string                 `protobuf:"bytes,1,opt,name=transformation_id,json=transformationId,proto3" json:"transformation_id,omitempty"`
	InputObjectId     string                 `protobuf:"bytes,2,opt,name=input_object_id,json=inputObjectId,proto3" json:"input_object_id,omitempty"`
	InputObjectType   string                 `protobuf:"bytes,3,opt,name=input_object_type,json=inputObjectType,proto3" json:"input_object_type,omitempty"`
	OutputObjectId    string                 `protobuf:"bytes,4,opt,name=output_object_id,json=outputObjectId,proto3" json:"output_object_id,omitempty"`
	OutputObjectType  string                 `protobuf:"bytes,5,opt,name=output_object_type,json=outputObjectType,proto3" json:"output_object_type,omitempty"`
	Component         string                 `protobuf:"bytes,6,opt,name=component,proto3" json:"component,omitempty"`
	ComponentVersion  string                 `protobuf:"bytes,7,opt,name=component_version,json=componentVersion,proto3" json:"component_version,omitempty"`
	ConfigurationHash string                 `protobuf:"bytes,8,opt,name=configuration_hash,json=configurationHash,proto3" json:"configuration_hash,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Status            TransformationStatus   `protobuf:"varint,11,opt,name=status,proto3,enum=cerbero.contracts.v1.TransformationStatus" json:"status,omitempty"`
	Error             *CerberoError          `protobuf:"bytes,12,opt,name=error,proto3,oneof" json:"error,omitempty"`
	ExecutionMode     ExecutionMode          `protobuf:"varint,13,opt,name=execution_mode,json=executionMode,proto3,enum=cerbero.contracts.v1.ExecutionMode" json:"execution_mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Transformation) Reset() {
	*x = Transformation{}
	mi := &file_cerbero_contracts_v1_transformation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transformation) ProtoMessage() {}

func (x *Transformation) ProtoReflect() protoreflect.Message {
	mi := &file_cerbero_contracts_v1_transformation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transformation.ProtoReflect.Descriptor instead.
func (*Transformation) Descriptor() ([]byte, []int) {
	return file_cerbero_contracts_v1_transformation_proto_rawDescGZIP(), []int{0}
}

func (x *Transformation) GetTransformationId() string {
	if x != nil {
		return x.TransformationId
	}
	return ""
}

func (x *Transformation) GetInputObjectId() string {
	if x != nil {
		return x.InputObjectId
	}
	return ""
}

func (x *Transformation) GetInputObjectType() string {
	if x != nil {
		return x.InputObjectType
	}
	return ""
}

func (x *Transformation) GetOutputObjectId() string {
	if x != nil {
		return x.OutputObjectId
	}
	return ""
}

func (x *Transformation) GetOutputObjectType() string {
	if x != nil {
		return x.OutputObjectType
	}
	return ""
}

func (x *Transformation) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Transformation) GetComponentVersion() string {
	if x != nil {
		return x.ComponentVersion
	}
	return ""
}

func (x *Transformation) GetConfigurationHash() string {
	if x != nil {
		return x.ConfigurationHash
	}
	return ""
}

func (x *Transformation) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Transformation) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Transformation) GetStatus() TransformationStatus {
	if x != nil {
		return x.Status
	}
	return TransformationStatus_TRANSFORMATION_STATUS_UNSPECIFIED
}

func (x *Transformation) GetError() *CerberoError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Transformation) GetExecutionMode() ExecutionMode {
	if x != nil {
		return x.ExecutionMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

var File_cerbero_contracts_v1_transformation_proto protoreflect.FileDescriptor

const file_cerbero_contracts_v1_transformation_proto_rawDesc = "" +
	"\n" +
	")cerbero/contracts/v1/transformation.proto\x12\x14cerbero.contracts.v1\x1a!cerbero/contracts/v1/common.proto\x1a cerbero/contracts/v1/error.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x05\n" +
	"\x0eTransformation\x12+\n" +
	"\x11transformation_id\x18\x01 \x01(\tR\x10transformationId\x12&\n" +
	"\x0finput_object_id\x18\x02 \x01(\tR\rinputObjectId\x12*\n" +
	"\x11input_object_type\x18\x03 \x01(\tR\x0finputObjectType\x12(\n" +
	"\x10output_object_id\x18\x04 \x01(\tR\x0eoutputObjectId\x12,\n" +
	"\x12output_object_type\x18\x05 \x01(\tR\x10outputObjectType\x12\x1c\n" +
	"\tcomponent\x18\x06 \x01(\tR\tcomponent\x12+\n" +
	"\x11component_version\x18\a \x01(\tR\x10componentVersion\x12-\n" +
	"\x12configuration_hash\x18\b \x01(\tR\x11configurationHash\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12B\n" +
	"\x06status\x18\v \x01(\x0e2*.cerbero.contracts.v1.TransformationStatusR\x06status\x12=\n" +
	"\x05error\x18\f \x01(\v2\".cerbero.contracts.v1.CerberoErrorH\x00R\x05error\x88\x01\x01\x12J\n" +
	"\x0eexecution_mode\x18\r \x01(\x0e2#.cerbero.contracts.v1.ExecutionModeR\rexecutionModeB\b\n" +
	"\x06_errorB4Z2cerbero/services/internal/contracts/v1;contractsv1b\x06proto3"

var (
	file_cerbero_contracts_v1_transformation_proto_rawDescOnce sync.Once
	file_cerbero_contracts_v1_transformation_proto_rawDescData []byte
)

func file_cerbero_contracts_v1_transformation_proto_rawDescGZIP() []byte {
	file_cerbero_contracts_v1_transformation_proto_rawDescOnce.Do(func() {
		file_cerbero_contracts_v1_transformation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_transformation_proto_rawDesc), len(file_cerbero_contracts_v1_transformation_proto_rawDesc)))
	})
	return file_cerbero_contracts_v1_transformation_proto_rawDescData
}

var file_cerbero_contracts_v1_transformation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cerbero_contracts_v1_transformation_proto_goTypes = []any{
	(*Transformation)(nil),        // 0: cerbero.contracts.v1.Transformation
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(TransformationStatus)(0),     // 2: cerbero.contracts.v1.TransformationStatus
	(*CerberoError)(nil),          // 3: cerbero.contracts.v1.CerberoError
	(ExecutionMode)(0),            // 4: cerbero.contracts.v1.ExecutionMode
}
var file_cerbero_contracts_v1_transformation_proto_depIdxs = []int32{
	1, // 0: cerbero.contracts.v1.Transformation.started_at:type_name -> google.protobuf.Timestamp
	1, // 1: cerbero.contracts.v1.Transformation.completed_at:type_name -> google.protobuf.Timestamp
	2, // 2: cerbero.contracts.v1.Transformation.status:type_name -> cerbero.contracts.v1.TransformationStatus
	3, // 3: cerbero.contracts.v1.Transformation.error:type_name -> cerbero.contracts.v1.CerberoError
	4, // 4: cerbero.contracts.v1.Transformation.execution_mode:type_name -> cerbero.contracts.v1.ExecutionMode
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_cerbero_contracts_v1_transformation_proto_init() }
func file_cerbero_contracts_v1_transformation_proto_init() {
	if File_cerbero_contracts_v1_transformation_proto != nil {
		return
	}
	file_cerbero_contracts_v1_common_proto_init()
	file_cerbero_contracts_v1_error_proto_init()
	file_cerbero_contracts_v1_transformation_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbero_contracts_v1_transformation_proto_rawDesc), len(file_cerbero_contracts_v1_transformation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbero_contracts_v1_transformation_proto_goTypes,
		DependencyIndexes: file_cerbero_contracts_v1_transformation_proto_depIdxs,
		MessageInfos:      file_cerbero_contracts_v1_transformation_proto_msgTypes,
	}.Build()
	File_cerbero_contracts_v1_transformation_proto = out.File
	file_cerbero_contracts_v1_transformation_proto_goTypes = nil
	file_cerbero_contracts_v1_transformation_proto_depIdxs = nil
}
