[package]
name = "cerbero-normalizer"
description = "CERBERO raw.persisted-to-OCSF normalizer."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cerbero-common = { path = "../cerbero-common" }
prost-types = "=0.14.4"
serde_json = "=1.0.145"

[lints]
workspace = true
